import type { Metadata } from "next";
import PngConverterClient from "./PngConverterClient";

const pageUrl = "https://repetigo.com/image-tools/png-converter";

export const metadata: Metadata = {
  title: "PNG Converter Free Online - PNG to JPG, WebP, GIF, ICO, PDF | RepetiGo",
  description:
    "Convert PNG to JPG, WebP, GIF, BMP, ICO, or PDF free online - one tool, every format. Batch convert multiple files. No sign-up, no watermark, 100% browser-based - nothing is ever uploaded.",
  alternates: { canonical: pageUrl },
  openGraph: {
    title: "PNG Converter Free Online - PNG to JPG, WebP, GIF, ICO, PDF | RepetiGo",
    description: "Convert PNG to JPG, WebP, GIF, BMP, ICO, or PDF free - one tool, every format. Batch convert. No sign-up, 100% browser-based.",
    type: "website",
    url: pageUrl,
  },
  twitter: {
    card: "summary_large_image",
    title: "PNG Converter Free - RepetiGo",
    description: "Convert PNG to any format free, one file or a batch. No sign-up, 100% browser-based.",
  },
  robots: { index: true, follow: true },
};

const content = String.raw`H1: PNG Converter Online Free. Convert PNG to JPG, WebP, GIF, BMP, ICO, or PDF - One Tool, No Sign-Up.
RepetiGo's free PNG Converter turns your PNG image into whichever format you actually need - JPG, WebP, GIF, BMP, ICO, or PDF - from a single tool. Upload a PNG, pick an output format, and download the result. Upload a batch and convert every file to the same format at once. No account, no watermark, and your files are never uploaded anywhere - conversion runs entirely inside your browser.

Different destinations need different formats: a portal upload usually wants JPG, a website wants WebP, a favicon wants ICO, an old system might only accept BMP, and a document workflow might want PDF. Instead of hunting for six separate converters, this page covers every common PNG output in one place.

✓ 6 Output Formats in One Tool   ✓ Batch Convert   ✓ Adjustable Quality Where It Applies   ✓ No Sign-Up   ✓ 100% Browser-Based - Nothing Uploaded

[ Convert PNG Free - No Sign-Up → repetigo.com/image-tools/png-converter ]

H2: What Format Should You Convert Your PNG To?
The right output format depends entirely on where the file is going. Converting to the wrong format either fails outright (a portal rejecting WebP) or wastes an opportunity (using PNG on a website when WebP would load faster). Here's how the common PNG output formats compare:

H3: PNG Output Format Comparison

Format
Best For
Transparency
Compression
When to Choose It
JPG
Photos, portal uploads, printing, email, general sharing
✗ Not supported
Lossy - smaller files
Universal compatibility is the priority, and you don't need transparency
WebP
Website images, faster page loads
✓ Supported
Lossy or lossless
You're optimizing images for a website and control what serves them
GIF
Simple flat-colour graphics, basic icons
✓ 1-bit only (fully on or off)
Limited to 256 colours
You specifically need the legacy GIF format, not photos or gradients
BMP
Legacy Windows software, some print or embedded systems
✓ Supported (uncompressed alpha)
None - uncompressed
An older system specifically requires BMP and file size doesn't matter
ICO
Favicons, Windows application icons
✓ Supported
None - wraps the image directly
You need a small icon file for a browser tab or a Windows app
PDF
Document workflows, sharing a single image as a document
✓ Supported (rendered as image)
None - PNG embedded as-is
The destination expects a document file, not an image file

💡 If you need SVG output instead - a scalable vector version of your PNG logo or icon - that's a different operation from format conversion (SVG is generated by tracing the image into vector paths, not by simply relabeling it). Use RepetiGo's dedicated PNG to SVG converter for real vector tracing.

H2: How to Convert PNG Online Free in 3 Steps.
H3: Step 1 - Upload Your PNG File
Click Select PNG Images or drag and drop your .png file - or several PNG files at once for batch conversion. There's no fixed file size cap, because everything runs on your own device. The converter works in any browser on any device.
H3: Step 2 - Choose Your Output Format
As soon as you upload, RepetiGo converts your PNG automatically to JPG at 90% quality by default. Change Output Format to switch between JPG, WebP, GIF, BMP, ICO, or PDF - every uploaded file re-converts automatically to the new format. For JPG and WebP, a quality slider appears so you can balance file size against visual detail; the other formats don't need a quality setting, since GIF, BMP, ICO, and PDF each work differently under the hood.
H3: Step 3 - Download Your Converted File
Click Download for a single file. For a batch, click Download ZIP to get every converted file in one archive. File names are preserved with the new extension (photo.png → photo.jpg). Because nothing was ever uploaded, there's nothing left on any server once you're done.

[ Convert PNG Free Now → repetigo.com/image-tools/png-converter ]

H2: ★ Batch PNG Conversion.
Whether it's a folder of product photos, a set of app icons, or a batch of scanned documents, converting PNG files one at a time is slow. RepetiGo's batch converter handles any number of files in one session:
Upload all PNG files at once - drag a multi-file selection or Ctrl+Click (Windows) / Cmd+Click (Mac) to multi-select.
Each file converts automatically to your chosen format as it's added.
Change the output format or quality at any point to re-convert every file in the batch.
Click Download ZIP to get one archive containing all the converted files, named identically to the originals.

💡 Every file in a batch converts to the same output format. If you need some PNGs as JPG and others as ICO, run them through in two separate batches - upload, convert, download, then start over with the next group and a different format.

H2: ★ Indian Use Cases - Who Uses a PNG Converter in India?
PNG is the default screenshot and graphic format on most Windows and Android devices in India, which means PNG files constantly need to become something else depending on where they're headed next.

Who Uses It
Common Need
Format They Choose
Students and job applicants
Converting a PNG screenshot or scanned certificate for a portal upload
JPG - smaller file, accepted everywhere
Web developers and agencies
Preparing PNG assets for faster-loading websites
WebP - smaller files without losing transparency
Small business owners
Creating a favicon or app icon from their PNG logo
ICO - the format browsers and Windows expect for icons
Print shops and DTP centres
Handling PNG files for older layout or print software
BMP - universally readable by legacy software
Freelancers and consultants
Sending a single design or screenshot as a shareable document
PDF - opens the same way on any device without an image viewer
Developers building simple graphics or older web content
Occasionally still need the legacy GIF format for basic icons
GIF - for flat-colour graphics only, not photos

H2: Why Use RepetiGo's PNG Converter?

Feature
RepetiGo
CloudConvert
Online-Convert.com
Windows Paint
Free to use
✓ Always free
✓ Free (25 conversions/day)
✓ Free with limits
✓ Free (built-in)
Multiple output formats in one tool
✓ JPG, WebP, GIF, BMP, ICO, PDF
✓ Many formats
✓ Many formats
~ Limited formats
Sign-up required
✓ Never
✗ Account for higher limits
~ Sometimes
✓ No account
Batch conversion
✓ Yes - upload any number of files
✓ Yes (limit applies)
~ Limited
✗ One file at a time
Files ever leave your device?
✗ Never - 100% browser-based
✓ Yes - uploaded to their servers
✓ Yes - uploaded to their servers
✓ Never - local
No watermark on output
✓ Always
✓ Yes
~ Some tiers add watermarks
✓ Yes

H2: Your Files Are Safe. Always.

Protection Layer
What It Means in Practice
🖥️ 100% Browser-Based Conversion
Your PNG is converted using your own device's processing power via the browser. It is never uploaded to any server.
🚫 Nothing Ever Leaves Your Device
Because conversion happens locally, there is no upload, no transfer, and nothing on any server for us to store or delete.
👁️ No Image Content Is Read
RepetiGo's code cannot see, analyse, or extract what's in your image - it only re-encodes pixel data on your own device.
🚫 No Account = No Data Profile
No sign-up means no personal data, no file history, and no usage profile is ever created.
🔒 Well Suited to Logos, Screenshots, and Personal Files
Because nothing is transmitted anywhere, this is a safe way to convert an unreleased design, a personal document, or a confidential screenshot.

[ Read Our Privacy Policy → /privacy-policy ]

H2: Common Questions About PNG Conversion.
H3: Q1: Does Converting PNG to JPG, WebP, or GIF Reduce Quality?
It depends on the format. JPG and WebP use lossy compression - at quality 90 and above, the result is visually indistinguishable from the PNG source, though some fine detail is technically discarded. GIF is more limited: it's restricted to 256 colours total and only 1-bit transparency (fully transparent or fully opaque, no partial transparency), so a GIF conversion can visibly change a PNG with smooth gradients or more than 256 colours. BMP, ICO, and PDF all preserve the image data without lossy compression, so there's no quality trade-off with those formats - the difference is file size and compatibility, not visual quality.
H3: Q2: What's the Difference Between ICO and PNG for a Favicon?
Browsers and operating systems have historically expected the ICO format specifically for favicons and Windows application icons, and some older browsers only support ICO, not PNG, in that role. Modern browsers do accept PNG favicons too, but ICO remains the safest, most universally compatible choice if you want the icon to work correctly everywhere, including in Windows shortcuts and older software. Converting your PNG logo to ICO here gives you a properly formatted favicon file.
H3: Q3: Can I Convert PNG to SVG With This Tool?
Not with this specific converter - PNG to SVG is a fundamentally different operation. Format conversion (what this page does) re-encodes the same pixel data in a new file format. Converting to SVG means tracing the image into vector paths - a different algorithm entirely, only useful for flat-colour logos, icons, and line art rather than photos. RepetiGo's dedicated PNG to SVG converter handles that with real vector tracing and adjustable detail levels.
H3: Q4: Why Does My Converted GIF Look Different From the Original PNG?
GIF is limited to a palette of 256 colours and 1-bit transparency, both stricter limits than PNG's millions of colours and full alpha channel. If your PNG has smooth gradients, photographic detail, or partially transparent areas, converting to GIF will visibly simplify those parts of the image, since GIF has no way to represent them precisely. This is expected behaviour of the GIF format itself, not a conversion error. GIF conversion works best on simple, flat-colour graphics like basic icons or logos with solid colours.
H3: Q5: How Do I Batch Convert Multiple PNG Files at Once?
Go to repetigo.com/image-tools/png-converter. Click Select PNG Images and choose multiple files using Ctrl+Click (Windows) or Cmd+Click (Mac), or drag several files into the upload area at once. Each file converts automatically to your chosen output format. Click Download ZIP to get an archive containing all the converted files, named identically to the originals. There's no file count limit per batch, and every file in the batch converts to the same format and quality setting.

H2: More Free Image Tools from RepetiGo.

Tool
What It Does
Link
PNG to SVG
Vectorize a PNG logo or icon into a real, scalable SVG
→ /image-tools/png-to-svg
PNG to JPG
Dedicated PNG to JPG converter with quality control
→ /image-tools/png-to-jpg
SVG Converter
Convert an SVG file into PNG or JPG at any size
→ /image-tools/svg-converter
Compress Image
Reduce file size further after conversion
→ /image-tools/compress-image
Resize Image
Resize a PNG before or after converting it
→ /image-tools/resize-image
All Image Tools
Complete free image tools suite
→ /image-tools

[ Convert PNG Free - No Sign-Up → repetigo.com/image-tools/png-converter ]
[ Explore All Image Tools → repetigo.com/image-tools ]`;

const faqSchemaQuestions = Array.from(content.matchAll(/H3: (Q\d+: [^\n]+)\n([\s\S]*?)(?=\nH3: Q\d+:|\nH2:|$)/g)).map((match) => [match[1], match[2].trim()] as const);

export default function PngConverterPage() {
  return (
    <PngConverterClient>
      <JsonLd />
      <article className="tool-seo-content compress-pdf-seo" id="png-converter-guide">
        <StructuredSeoCopy content={content} />
      </article>
    </PngConverterClient>
  );
}

type SeoTableData = { headers: string[]; rows: string[][] };
const CALLOUT_EMOJI = ["💡", "🇮🇳", "🔒", "🖨️", "📱", "✅", "⚠️", "🖥️", "🔁", "🔄", "★"];

function StructuredSeoCopy({ content: source }: { content: string }) {
  const blocks = source.replace(/(^|\n)(H[123]: [^\n]+)\n/g, "$1\n$2\n\n").split(/\n{2,}/).map((block) => block.trim()).filter(Boolean);
  return (
    <>
      {blocks.map((block, index) => {
        const lines = block.split("\n").map((line) => line.trim()).filter(Boolean);
        const first = lines[0];
        if (first.startsWith("H1: ")) return <h1 key={index}>{first.slice(4)}</h1>;
        if (first.startsWith("H2: ")) return <h2 key={index}>{first.slice(4)}</h2>;
        if (first.startsWith("H3: ")) {
          const heading = first.slice(4);
          const body = lines.slice(1);
          return (
            <section className="tool-seo-copy-block" key={index}>
              <h3>{heading}</h3>
              {body.map((line) => <p key={line}>{renderInlineMappedLinks(line)}</p>)}
            </section>
          );
        }
        const table = getKnownTable(lines);
        if (table) return <SeoTable key={index} {...table} />;
        if (first.startsWith("✓ ")) {
          return <div className="tool-seo-badges" key={index}>{first.split(/\s{2,}/).map((item) => <span key={item}>{item}</span>)}</div>;
        }
        if (lines.length && lines.every((line) => line.startsWith("[ ") && line.endsWith(" ]"))) {
          return <div className="tool-seo-cta-stack" key={index}>{lines.map((line) => <CtaLine key={line} text={line} />)}</div>;
        }
        if (CALLOUT_EMOJI.some((emoji) => first.startsWith(emoji))) {
          return <aside className="tool-seo-callout" key={index}>{lines.map((line) => <p key={line}>{renderInlineMappedLinks(line)}</p>)}</aside>;
        }
        return <div className="tool-seo-copy-paragraph" key={index}>{lines.map((line) => <p key={line}>{renderInlineMappedLinks(line)}</p>)}</div>;
      })}
    </>
  );
}

function getKnownTable(lines: string[]): SeoTableData | null {
  if (lines[0] === "Format" && lines[1] === "Best For") return { headers: ["Format", "Best For", "Transparency", "Compression", "When to Choose It"], rows: chunkRows(lines.slice(5), 5) };
  if (lines[0] === "Who Uses It" && lines[1] === "Common Need") return { headers: ["Who Uses It", "Common Need", "Format They Choose"], rows: chunkRows(lines.slice(3), 3) };
  if (lines[0] === "Feature" && lines[1] === "RepetiGo") return { headers: ["Feature", "RepetiGo", "CloudConvert", "Online-Convert.com", "Windows Paint"], rows: chunkRows(lines.slice(5), 5) };
  if (lines[0] === "Protection Layer" && lines[1] === "What It Means in Practice") return { headers: ["Protection Layer", "What It Means in Practice"], rows: chunkRows(lines.slice(2), 2) };
  if (lines[0] === "Tool" && lines[1] === "What It Does" && lines[2] === "Link") return { headers: ["Tool", "What It Does", "Link"], rows: chunkRows(lines.slice(3), 3) };
  return null;
}

function chunkRows(values: string[], size: number) {
  const rows: string[][] = [];
  for (let index = 0; index < values.length; index += size) rows.push(values.slice(index, index + size));
  return rows;
}

function SeoTable({ headers, rows }: SeoTableData) {
  return (
    <div className="tool-seo-table-wrap">
      <table>
        <thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead>
        <tbody>
          {rows.map((row) => <tr key={row.join("|")}>{row.map((cell, index) => <td key={cell + "-" + index}>{renderTableCell(cell)}</td>)}</tr>)}
        </tbody>
      </table>
    </div>
  );
}

function CtaLine({ text }: { text: string }) {
  const inner = text.slice(2, -2);
  const [, label = inner, href = ""] = inner.match(/^(.*?)\s*(?:→)\s*(.+)$/) || [];
  const mappedHref = mapSeoRoute(href || "");
  return <a className="tool-seo-inline-cta" href={mappedHref || "#png-converter-guide"}>{label}{mappedHref ? <span>{"→"}</span> : null}</a>;
}

function renderTableCell(cell: string) {
  const cleaned = cell.replace(/^→\s*/, "").trim();
  const href = mapSeoRoute(cleaned);
  if (!href) return renderInlineMappedLinks(cell);
  return <a className="tool-seo-table-link" href={href}>{getRouteLabel(href)}</a>;
}

function renderInlineMappedLinks(text: string) {
  const parts = text.split(/(repetigo\.com\/(?:image-tools\/[a-z-]*|pricing)\/?|\/image-tools\/[a-z-]*\/?|\/image-tools\/?|\/products\/printpilot\/?|\/privacy-policy\/?|\/pricing\/?)/g);
  return parts.map((part, index) => {
    const href = mapSeoRoute(part.startsWith("repetigo.com") ? "https://" + part : part);
    if (!href) return part;
    return <a href={href} key={part + "-" + index}>{getRouteLabel(href)}</a>;
  });
}

function mapSeoRoute(route: string) {
  const cleanRoute = route.trim().replace(/^(https?:\/\/)?(www\.)?repetigo\.com/i, "").replace(/\/$/, "");
  const routeMap: Record<string, string> = {
    "/image-tools": "/image-tools",
    "/image-tools/png-converter": "/image-tools/png-converter",
    "/image-tools/png-to-svg": "/image-tools/png-to-svg",
    "/image-tools/png-to-jpg": "/image-tools/png-to-jpg",
    "/image-tools/svg-converter": "/image-tools/svg-converter",
    "/image-tools/compress-image": "/image-tools/compress-image",
    "/image-tools/resize-image": "/image-tools/resize-image",
    "/products/printpilot": "/print-automation",
    "/privacy-policy": "/privacy-policy",
    "/pricing": "/pricing",
  };
  return routeMap[cleanRoute] || (cleanRoute.startsWith("/image-tools") ? cleanRoute : "");
}

function getRouteLabel(href: string) {
  const labels: Record<string, string> = {
    "/image-tools": "Explore All Image Tools",
    "/image-tools/png-converter": "Open PNG Converter",
    "/image-tools/png-to-svg": "Open PNG to SVG",
    "/image-tools/png-to-jpg": "Open PNG to JPG",
    "/image-tools/svg-converter": "Open SVG Converter",
    "/image-tools/compress-image": "Open Compress Image",
    "/image-tools/resize-image": "Open Resize Image",
    "/print-automation": "Learn About PrintPilot",
    "/privacy-policy": "Read Privacy Policy",
    "/pricing": "Start Free Trial",
  };
  return labels[href] || "Open Tool";
}

function JsonLd() {
  const softwareApplication = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "RepetiGo PNG Converter", applicationCategory: "UtilitiesApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "INR" }, description: "Free online PNG converter supporting JPG, WebP, GIF, BMP, ICO, and PDF output with batch conversion. Runs entirely in the browser - no file is ever uploaded to a server.", url: pageUrl };
  const howTo = { "@context": "https://schema.org", "@type": "HowTo", name: "How to Convert PNG Online Free", step: [{ "@type": "HowToStep", name: "Upload PNG", text: "Upload Your PNG File" }, { "@type": "HowToStep", name: "Choose Format", text: "Choose Your Output Format" }, { "@type": "HowToStep", name: "Download", text: "Download Your Converted File" }] };
  const faqPage = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqSchemaQuestions.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };
  const breadcrumb = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://repetigo.com/" }, { "@type": "ListItem", position: 2, name: "Image Tools", item: "https://repetigo.com/image-tools" }, { "@type": "ListItem", position: 3, name: "PNG Converter", item: pageUrl }] };

  return <>{[softwareApplication, howTo, faqPage, breadcrumb].map((schema) => <script key={schema["@type"]} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}</>;
}
