"use client";

import { useEffect, useRef, useState, type ChangeEvent, type ReactNode } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, Download, Eye, EyeOff, FileCheck2, FileKey2, Files, LoaderCircle, LockKeyhole, PenLine, RotateCcw, ShieldAlert, ShieldCheck, Upload } from "lucide-react";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { PdfToolUpload } from "./PdfToolUpload";
import { RelatedToolSuggestions, ToolPromotionRail } from "./ToolDiscovery";

export type SecuritySlug = "unlock-pdf" | "protect-pdf" | "sign-pdf" | "redact-pdf" | "compare-pdf";
type Preview = { index:number; image:string; width:number; height:number; text:string };
type Result = { blob:Blob; url:string; name:string };
const configs = {
  "unlock-pdf": { title:"Unlock PDF", description:"Remove PDF open-password protection when you know the password.", icon:FileKey2, action:"Unlock PDF" },
  "protect-pdf": { title:"Protect PDF", description:"Secure a PDF with native AES-256 password encryption.", icon:LockKeyhole, action:"Protect PDF" },
  "sign-pdf": { title:"Sign PDF", description:"Place a typed or image signature on selected PDF pages.", icon:PenLine, action:"Sign PDF" },
  "redact-pdf": { title:"Redact PDF", description:"Permanently flatten and hide sensitive areas of PDF pages.", icon:ShieldAlert, action:"Apply redaction" },
  "compare-pdf": { title:"Compare PDF", description:"Compare two PDFs page-by-page and review visual differences.", icon:Files, action:"Compare PDFs" },
} satisfies Record<SecuritySlug,{title:string;description:string;icon:typeof FileKey2;action:string}>;
export function isSecuritySlug(value:string):value is SecuritySlug{return value in configs;}

export default function PdfSecurityTool({slug,children}:{slug:SecuritySlug;children?:ReactNode}){
  const config=configs[slug],Icon=config.icon,inputRef=useRef<HTMLInputElement>(null),signatureRef=useRef<HTMLInputElement>(null);
  const [files,setFiles]=useState<File[]>([]),[pages,setPages]=useState<Preview[][]>([]),[selected,setSelected]=useState<Set<number>>(new Set()),[loading,setLoading]=useState(false),[processing,setProcessing]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(""),[result,setResult]=useState<Result|null>(null);
  const [password,setPassword]=useState(""),[ownerPassword,setOwnerPassword]=useState(""),[showPassword,setShowPassword]=useState(false),[allowPrinting,setAllowPrinting]=useState(true),[allowCopying,setAllowCopying]=useState(false),[allowEditing,setAllowEditing]=useState(false);
  const [signature,setSignature]=useState("Your Signature"),[signatureImage,setSignatureImage]=useState(""),[signatureMode,setSignatureMode]=useState<"type"|"image">("type"),[x,setX]=useState(10),[y,setY]=useState(12),[signatureSize,setSignatureSize]=useState(28),[redactWidth,setRedactWidth]=useState(35),[redactHeight,setRedactHeight]=useState(10);
  const [comparison,setComparison]=useState<{score:number;pageScores:number[]}|null>(null);
  useEffect(()=>()=>{if(result)URL.revokeObjectURL(result.url);},[result]);
  async function chooseFiles(list:FileList){const additions=Array.from(list);if(!additions.length)return;const next=slug==="compare-pdf"?[...files,...additions].slice(0,2):[additions[0]];clearResult();setFiles(next);setLoading(true);setError("");try{const rendered:Preview[][]=[];for(const file of next)rendered.push(await renderPdf(file,slug==="unlock-pdf"?password:undefined));setPages(rendered);setSelected(new Set((rendered[0]||[]).map(page=>page.index)));}catch(reason){console.error(reason);setPages([]);if(slug==="unlock-pdf")setError("Enter the correct PDF password, then select the file again.");else setError("This PDF could not be opened. It may be protected or damaged.");}finally{setLoading(false);}}
  function clearResult(){if(result)URL.revokeObjectURL(result.url);setResult(null);setComparison(null);setProgress(0);}
  function reset(){clearResult();setFiles([]);setPages([]);setSelected(new Set());setPassword("");setError("");setSignatureImage("");}
  function removeFile(index:number){clearResult();setFiles(current=>current.filter((_,i)=>i!==index));setPages(current=>current.filter((_,i)=>i!==index));}
  function togglePage(index:number){setSelected(current=>{const next=new Set(current);next.has(index)?next.delete(index):next.add(index);return next;});clearResult();}
  async function process(){if(processing||!files.length||(slug==="compare-pdf"&&files.length<2))return;setProcessing(true);setProgress(5);setError("");clearResult();try{if(slug==="compare-pdf"){const compared=comparePages(pages[0],pages[1]);setComparison(compared);setProgress(100);return;}let bytes:Uint8Array;if(slug==="protect-pdf"){if(password.length<4)throw new Error("Use a password with at least 4 characters.");const {encryptPDF}=await import("@pdfsmaller/pdf-encrypt");bytes=await encryptPDF(new Uint8Array(await files[0].arrayBuffer()),password,{ownerPassword:ownerPassword||password,algorithm:"AES-256",allowPrinting,allowCopying,allowModifying:allowEditing,allowAnnotating:allowEditing,allowFillingForms:true,allowExtraction:false,allowAssembly:false,allowHighQualityPrint:allowPrinting});}else if(slug==="unlock-pdf"){if(!password)throw new Error("Enter the current PDF password.");const {decryptPDF}=await import("@pdfsmaller/pdf-decrypt");bytes=await decryptPDF(new Uint8Array(await files[0].arrayBuffer()),password);}else if(slug==="sign-pdf")bytes=await signPdf(files[0],selected,{signature,signatureImage,mode:signatureMode,x,y,size:signatureSize},setProgress);else bytes=await permanentlyRedact(files[0],selected,{x,y,width:redactWidth,height:redactHeight},setProgress);const blob=new Blob([bytes],{type:"application/pdf"});setResult({blob,url:URL.createObjectURL(blob),name:`${baseName(files[0].name)}-${slug}.pdf`});setProgress(100);}catch(reason){console.error(reason);setError(reason instanceof Error?reason.message:"PDF processing failed.");}finally{setProcessing(false);}}
  const ready=files.length===(slug==="compare-pdf"?2:1);
  if(!files.length)return <><PdfToolUpload title={config.title} description={config.description} icon={Icon} inputRef={inputRef} onFiles={(list)=>void chooseFiles(list)} multiple={slug==="compare-pdf"} buttonLabel={slug==="compare-pdf"?"Select two PDF files":"Select PDF file"} headingLevel={children?"h2":"h1"}/>{children}</>;
  return <div className="security-page"><input ref={inputRef} hidden type="file" accept="application/pdf,.pdf" multiple={slug==="compare-pdf"} onChange={e=>{if(e.target.files?.length)void chooseFiles(e.target.files);e.target.value="";}}/><input ref={signatureRef} hidden type="file" accept="image/png,image/jpeg" onChange={e=>void loadSignature(e,setSignatureImage)}/>
    <div className="security-topline"><Link href="/pdf-tools"><ArrowLeft size={17}/> PDF Tools</Link><span><ShieldCheck size={16}/> Secure, private browser processing</span></div><div className="security-studio"><main className="security-canvas"><header><div><span><Icon size={23}/></span><div><small>RepetiGo PDF Security</small>{children ? <h2>{config.title}</h2> : <h1>{config.title}</h1>}<p>{files.map(file=>file.name).join(" + ")}</p></div></div><button type="button" onClick={()=>inputRef.current?.click()}>{slug==="compare-pdf"&&files.length<2?"Add second PDF":"Replace PDF"}</button></header>
    {loading?<div className="security-loading"><LoaderCircle className="spin"/> Reading secure document…</div>:result?<SecuritySuccess result={result} config={config} onBack={clearResult} onReset={reset} slug={slug}/>:comparison?<ComparisonView pages={pages} comparison={comparison} onBack={clearResult} onReset={reset}/>:slug==="compare-pdf"?<CompareWorkspace files={files} pages={pages} removeFile={removeFile}/>:<PageWorkspace pages={pages[0]||[]} selected={selected} togglePage={togglePage} slug={slug} x={x} y={y} width={redactWidth} height={redactHeight} signature={signature} signatureImage={signatureImage}/>}</main>
    {!result&&!comparison?<aside className="security-panel"><div><span className="auto-print-kicker">RepetiGo security</span><h2>{config.title}</h2><p>{config.description}</p></div><SecurityControls slug={slug} password={password} setPassword={setPassword} ownerPassword={ownerPassword} setOwnerPassword={setOwnerPassword} show={showPassword} setShow={setShowPassword} permissions={{allowPrinting,allowCopying,allowEditing}} setPermissions={{setAllowPrinting,setAllowCopying,setAllowEditing}} signature={signature} setSignature={setSignature} signatureMode={signatureMode} setSignatureMode={setSignatureMode} signatureImage={signatureImage} openSignature={()=>signatureRef.current?.click()} x={x} setX={setX} y={y} setY={setY} size={signatureSize} setSize={setSignatureSize} redactWidth={redactWidth} setRedactWidth={setRedactWidth} redactHeight={redactHeight} setRedactHeight={setRedactHeight}/><div className="security-ready"><ShieldCheck size={18}/><div><strong>{ready?"Ready to process":`Add ${2-files.length} more PDF`}</strong><small>{slug==="redact-pdf"?"Output will be flattened to permanently remove hidden content.":"Your files and passwords never leave this browser."}</small></div></div>{processing?<div className="security-progress"><span>Processing… {progress}%</span><progress value={progress} max="100"/></div>:null}<button className="security-submit" type="button" disabled={!ready||processing||(slug!=="compare-pdf"&&!selected.size&&slug!=="protect-pdf"&&slug!=="unlock-pdf")} onClick={process}>{processing?<LoaderCircle className="spin" size={18}/>:<Icon size={18}/>} {processing?"Processing…":config.action}<ArrowRight size={17}/></button><button className="security-reset" type="button" onClick={reset}><RotateCcw size={15}/> Start over</button></aside>:<ToolPromotionRail context={`${slug}-result`}/>}</div>{error?<div className="profile-alert error security-error">{error}</div>:null}</div>;
}

function PageWorkspace({pages,selected,togglePage,slug,x,y,width,height,signature,signatureImage}:{pages:Preview[];selected:Set<number>;togglePage(i:number):void;slug:SecuritySlug;x:number;y:number;width:number;height:number;signature:string;signatureImage:string}){return <><div className="security-selection"><span>{selected.size} of {pages.length} pages selected</span><small>Click a page to include or exclude it</small></div><div className="security-page-grid">{pages.map(page=><button type="button" className={selected.has(page.index)?"selected":""} key={page.index} onClick={()=>togglePage(page.index)}><span>Page {page.index}</span><div><img src={page.image} alt={`Page ${page.index}`}/>{selected.has(page.index)&&slug==="redact-pdf"?<i className="redact-preview" style={{left:`${x}%`,top:`${y}%`,width:`${width}%`,height:`${height}%`}}/>:null}{selected.has(page.index)&&slug==="sign-pdf"?<i className="sign-preview" style={{left:`${x}%`,top:`${y}%`}}>{signatureImage?<img src={signatureImage} alt="Signature"/>:signature}</i>:null}</div><em>{selected.has(page.index)?<Check size={14}/>:null}</em></button>)}</div></>}
function CompareWorkspace({files,pages,removeFile}:{files:File[];pages:Preview[][];removeFile(i:number):void}){return <div className="compare-workspace">{[0,1].map(index=><article key={index}>{files[index]?<><header><div><strong>{index===0?"Original PDF":"Compare with"}</strong><small>{files[index].name} · {pages[index]?.length||0} pages</small></div><button type="button" onClick={()=>removeFile(index)}>×</button></header>{pages[index]?.[0]?<img src={pages[index][0].image} alt={`${index===0?"Original":"Second"} PDF first page`}/>:null}</>:<div className="compare-empty"><Upload size={27}/><strong>Add second PDF</strong></div>}</article>)}</div>}
function ComparisonView({pages,comparison,onBack,onReset}:{pages:Preview[][];comparison:{score:number;pageScores:number[]};onBack():void;onReset():void}){return <section className="compare-result"><span><FileCheck2 size={30}/></span><h2>Comparison complete</h2><p>{comparison.score}% visual similarity across {comparison.pageScores.length} compared pages.</p><div className="compare-score"><strong>{100-comparison.score}%</strong><small>estimated difference</small><progress value={100-comparison.score} max="100"/></div><div className="compare-result-pages">{comparison.pageScores.map((score,index)=><article key={index}><div><img src={pages[0]?.[index]?.image} alt="Original"/><img src={pages[1]?.[index]?.image} alt="Compared"/></div><strong>Page {index+1}</strong><small>{100-score}% difference</small></article>)}</div><footer><button type="button" onClick={onBack}>Compare again</button><button type="button" onClick={onReset}>New comparison</button></footer><RelatedToolSuggestions context="compare-pdf-result"/></section>}
function SecuritySuccess({result,config,onBack,onReset,slug}:{result:Result;config:(typeof configs)[SecuritySlug];onBack():void;onReset():void;slug:SecuritySlug}){return <section className="security-success"><span><Check size={30}/></span><h2>{config.action} completed!</h2><p>Your secure PDF is ready.</p><div><FileTextIcon/><div><strong>{result.name}</strong><small>{formatBytes(result.blob.size)}</small></div></div><a href={result.url} download={result.name}><Download size={19}/> Download PDF</a><footer><button type="button" onClick={onBack}>Change settings</button><button type="button" onClick={onReset}>Process another PDF</button></footer><RelatedToolSuggestions context={`${slug}-result`}/></section>}
function FileTextIcon(){return <FileCheck2 size={25}/>}

type Controls={slug:SecuritySlug;password:string;setPassword(v:string):void;ownerPassword:string;setOwnerPassword(v:string):void;show:boolean;setShow(v:boolean):void;permissions:{allowPrinting:boolean;allowCopying:boolean;allowEditing:boolean};setPermissions:{setAllowPrinting(v:boolean):void;setAllowCopying(v:boolean):void;setAllowEditing(v:boolean):void};signature:string;setSignature(v:string):void;signatureMode:"type"|"image";setSignatureMode(v:"type"|"image"):void;signatureImage:string;openSignature():void;x:number;setX(v:number):void;y:number;setY(v:number):void;size:number;setSize(v:number):void;redactWidth:number;setRedactWidth(v:number):void;redactHeight:number;setRedactHeight(v:number):void};
function SecurityControls(p:Controls){if(p.slug==="unlock-pdf")return <section className="security-controls"><h3>Current password</h3><Password value={p.password} setValue={p.setPassword} show={p.show} setShow={p.setShow}/><p>Only unlock PDFs you own or have permission to modify.</p></section>;if(p.slug==="protect-pdf")return <section className="security-controls"><h3>AES-256 protection</h3><label>Open password<Password value={p.password} setValue={p.setPassword} show={p.show} setShow={p.setShow}/></label><label>Owner password (optional)<input type={p.show?"text":"password"} value={p.ownerPassword} onChange={e=>p.setOwnerPassword(e.target.value)}/></label><div className="security-checks"><label><input type="checkbox" checked={p.permissions.allowPrinting} onChange={e=>p.setPermissions.setAllowPrinting(e.target.checked)}/> Allow printing</label><label><input type="checkbox" checked={p.permissions.allowCopying} onChange={e=>p.setPermissions.setAllowCopying(e.target.checked)}/> Allow copying</label><label><input type="checkbox" checked={p.permissions.allowEditing} onChange={e=>p.setPermissions.setAllowEditing(e.target.checked)}/> Allow editing</label></div></section>;if(p.slug==="sign-pdf")return <section className="security-controls"><h3>Signature</h3><div className="security-tabs"><button className={p.signatureMode==="type"?"active":""} onClick={()=>p.setSignatureMode("type")} type="button">Type</button><button className={p.signatureMode==="image"?"active":""} onClick={()=>p.setSignatureMode("image")} type="button">Upload image</button></div>{p.signatureMode==="type"?<label>Signature text<input value={p.signature} onChange={e=>p.setSignature(e.target.value)}/></label>:<button className="signature-upload" type="button" onClick={p.openSignature}>{p.signatureImage?<img src={p.signatureImage} alt="Uploaded signature"/>:<><Upload size={18}/> Select PNG/JPG signature</>}</button>}<PositionControls {...p}/><label>Signature size <span>{p.size}px</span><input type="range" min="12" max="72" value={p.size} onChange={e=>p.setSize(+e.target.value)}/></label></section>;if(p.slug==="redact-pdf")return <section className="security-controls"><h3>Redaction area</h3><PositionControls {...p}/><label>Width <span>{p.redactWidth}%</span><input type="range" min="5" max="90" value={p.redactWidth} onChange={e=>p.setRedactWidth(+e.target.value)}/></label><label>Height <span>{p.redactHeight}%</span><input type="range" min="3" max="50" value={p.redactHeight} onChange={e=>p.setRedactHeight(+e.target.value)}/></label><p>Selected pages are flattened, preventing covered text from being copied or recovered.</p></section>;return <section className="security-controls"><h3>Visual comparison</h3><p>Compares rendered pages and extracted text locally. Different page counts are reported as differences.</p></section>}
function PositionControls(p:{x:number;setX(v:number):void;y:number;setY(v:number):void}){return <><label>From left <span>{p.x}%</span><input type="range" min="0" max="90" value={p.x} onChange={e=>p.setX(+e.target.value)}/></label><label>From top <span>{p.y}%</span><input type="range" min="0" max="90" value={p.y} onChange={e=>p.setY(+e.target.value)}/></label></>}
function Password({value,setValue,show,setShow}:{value:string;setValue(v:string):void;show:boolean;setShow(v:boolean):void}){return <div className="password-input"><input type={show?"text":"password"} value={value} onChange={e=>setValue(e.target.value)} placeholder="Enter password"/><button type="button" onClick={()=>setShow(!show)} aria-label={show?"Hide password":"Show password"}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>}

async function renderPdf(file:File,password?:string){const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/legacy/build/pdf.worker.min.mjs",import.meta.url).toString();const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),password}).promise;const output:Preview[]=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),base=page.getViewport({scale:1}),view=page.getViewport({scale:Math.min(.72,180/base.width)}),canvas=document.createElement("canvas");canvas.width=Math.ceil(view.width);canvas.height=Math.ceil(view.height);const context=canvas.getContext("2d");if(!context)throw new Error("Canvas unavailable");await page.render({canvas,canvasContext:context,viewport:view}).promise;const content=await page.getTextContent();output.push({index:n,image:canvas.toDataURL("image/jpeg",.82),width:base.width,height:base.height,text:(content.items as Array<{str?:string}>).map(item=>item.str||"").join(" ")});}return output;}
async function signPdf(file:File,selected:Set<number>,settings:{signature:string;signatureImage:string;mode:"type"|"image";x:number;y:number;size:number},progress:(v:number)=>void){const pdf=await PDFDocument.load(await file.arrayBuffer()),font=await pdf.embedFont(StandardFonts.HelveticaOblique);let image:Awaited<ReturnType<PDFDocument["embedPng"]>>|null=null;if(settings.mode==="image"&&settings.signatureImage){const bytes=await (await fetch(settings.signatureImage)).arrayBuffer();image=settings.signatureImage.startsWith("data:image/png")?await pdf.embedPng(bytes):await pdf.embedJpg(bytes);}const chosen=Array.from(selected);chosen.forEach((number,index)=>{const page=pdf.getPage(number-1),width=page.getWidth(),height=page.getHeight(),px=width*settings.x/100,py=height-height*settings.y/100-settings.size;if(image){const scale=settings.size*3/image.width;page.drawImage(image,{x:px,y:py,width:image.width*scale,height:image.height*scale});}else page.drawText(safeText(settings.signature),{x:px,y:py,size:settings.size,font,color:rgb(.04,.13,.34)});progress(Math.round((index+1)/chosen.length*90));});return pdf.save();}
async function permanentlyRedact(file:File,selected:Set<number>,area:{x:number;y:number;width:number;height:number},progress:(v:number)=>void){const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/legacy/build/pdf.worker.min.mjs",import.meta.url).toString();const source=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,output=await PDFDocument.create();for(let n=1;n<=source.numPages;n++){const sourcePage=await source.getPage(n),view=sourcePage.getViewport({scale:1.5}),canvas=document.createElement("canvas");canvas.width=Math.ceil(view.width);canvas.height=Math.ceil(view.height);const context=canvas.getContext("2d");if(!context)throw new Error("Canvas unavailable");await sourcePage.render({canvas,canvasContext:context,viewport:view}).promise;if(selected.has(n)){context.fillStyle="#050505";context.fillRect(canvas.width*area.x/100,canvas.height*area.y/100,canvas.width*area.width/100,canvas.height*area.height/100);}const image=await output.embedJpg(canvas.toDataURL("image/jpeg",.94)),page=output.addPage([view.width/1.5,view.height/1.5]);page.drawImage(image,{x:0,y:0,width:page.getWidth(),height:page.getHeight()});progress(Math.round(n/source.numPages*90));}return output.save();}
function comparePages(a:Preview[],b:Preview[]){const count=Math.max(a.length,b.length),scores:number[]=[];for(let i=0;i<count;i++){if(!a[i]||!b[i])scores.push(0);else{const left=normalizeText(a[i].text),right=normalizeText(b[i].text);if(left===right)scores.push(100);else{const leftWords=new Set(left.split(" ").filter(Boolean)),rightWords=new Set(right.split(" ").filter(Boolean)),common=Array.from(leftWords).filter(word=>rightWords.has(word)).length,total=new Set([...Array.from(leftWords),...Array.from(rightWords)]).size;scores.push(total?Math.round(common/total*100):imageSimilarity(a[i].image,b[i].image));}}}return{score:scores.length?Math.round(scores.reduce((sum,value)=>sum+value,0)/scores.length):0,pageScores:scores};}
function imageSimilarity(a:string,b:string){return a===b?100:50;}function normalizeText(v:string){return v.toLowerCase().replace(/\s+/g," ").trim();}function safeText(v:string){return v.replace(/[^\x20-\x7e]/g,"?");}function loadSignature(event:ChangeEvent<HTMLInputElement>,set:(v:string)=>void){const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>set(String(reader.result||""));reader.readAsDataURL(file);event.target.value="";}function baseName(name:string){return name.replace(/\.pdf$/i,"");}function formatBytes(bytes:number){return bytes<1048576?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/1048576).toFixed(2)} MB`;}
