"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, Clipboard, Download, Eye, FileCode2, FileSearch, LoaderCircle, RotateCcw, ShieldCheck } from "lucide-react";
import { PdfToolUpload } from "./PdfToolUpload";
import { RelatedToolSuggestions, ToolPromotionRail } from "./ToolDiscovery";

type PageData={index:number;image:string;lines:TextLine[];text:string};
type TextLine={text:string;fontSize:number;bold:boolean;x:number;y:number};

export default function PdfToMarkdownTool(){
  const inputRef=useRef<HTMLInputElement>(null);const [file,setFile]=useState<File|null>(null),[pages,setPages]=useState<PageData[]>([]),[selected,setSelected]=useState<Set<number>>(new Set()),[loading,setLoading]=useState(false),[processing,setProcessing]=useState(false),[progress,setProgress]=useState(0),[markdown,setMarkdown]=useState(""),[error,setError]=useState(""),[copied,setCopied]=useState(false),[preview,setPreview]=useState<"source"|"preview">("source"),[includePageBreaks,setIncludePageBreaks]=useState(true),[detectHeadings,setDetectHeadings]=useState(true),[preserveLinks,setPreserveLinks]=useState(true);
  const [downloadUrl,setDownloadUrl]=useState("");useEffect(()=>()=>{if(downloadUrl)URL.revokeObjectURL(downloadUrl);},[downloadUrl]);
  async function chooseFile(list:FileList){const next=list[0];if(!next)return;clearResult();setFile(next);setPages([]);setLoading(true);setError("");try{const extracted=await extractPages(next);setPages(extracted);setSelected(new Set(extracted.map(page=>page.index)));if(!extracted.some(page=>page.text.trim()))setError("No selectable text was found. This appears to be a scanned PDF—run OCR PDF first.");}catch(reason){console.error(reason);setFile(null);setError("This PDF could not be opened. It may be protected or damaged.");}finally{setLoading(false);}}
  function clearResult(){if(downloadUrl)URL.revokeObjectURL(downloadUrl);setDownloadUrl("");setMarkdown("");setProgress(0);setCopied(false);}
  function reset(){clearResult();setFile(null);setPages([]);setSelected(new Set());setError("");}
  function toggle(index:number){clearResult();setSelected(current=>{const next=new Set(current);next.has(index)?next.delete(index):next.add(index);return next;});}
  async function convert(){if(!file||!selected.size||processing)return;setProcessing(true);setProgress(8);setError("");clearResult();try{const chosen=pages.filter(page=>selected.has(page.index));const output=chosen.map((page,index)=>{setProgress(Math.round((index+1)/chosen.length*90));return pageToMarkdown(page,{detectHeadings,preserveLinks});}).filter(Boolean).join(includePageBreaks?"\n\n---\n\n":"\n\n");if(!output.trim())throw new Error("No selectable text was found on the selected pages. Use OCR PDF for scanned documents.");setMarkdown(output);const blob=new Blob([output],{type:"text/markdown;charset=utf-8"});setDownloadUrl(URL.createObjectURL(blob));setProgress(100);}catch(reason){setError(reason instanceof Error?reason.message:"PDF could not be converted to Markdown.");}finally{setProcessing(false);}}
  async function copyMarkdown(){await navigator.clipboard.writeText(markdown);setCopied(true);setTimeout(()=>setCopied(false),1800);}
  if(!file)return <PdfToolUpload title="PDF to Markdown" description="Convert PDF text into clean, editable Markdown in your browser." icon={FileCode2} inputRef={inputRef} onFiles={files=>void chooseFile(files)} multiple={false} buttonLabel="Select PDF file"/>;
  return <div className="markdown-tool-page"><input ref={inputRef} hidden type="file" accept="application/pdf,.pdf" onChange={event=>{if(event.target.files?.length)void chooseFile(event.target.files);event.target.value="";}}/><div className="markdown-topline"><Link href="/pdf-tools"><ArrowLeft size={17}/> PDF Tools</Link><span><ShieldCheck size={16}/> Free · Private browser processing</span></div><div className="markdown-studio"><main className="markdown-canvas"><header><div><span><FileCode2 size={23}/></span><div><small>RepetiGo PDF Intelligence</small><h1>PDF to Markdown</h1><p>{file.name} · {pages.length} pages · {formatBytes(file.size)}</p></div></div><button type="button" onClick={()=>inputRef.current?.click()}>Replace PDF</button></header>
    {loading?<div className="markdown-loading"><LoaderCircle className="spin"/> Extracting document structure…</div>:markdown?<MarkdownResult markdown={markdown} setMarkdown={setMarkdown} preview={preview} setPreview={setPreview} copy={copyMarkdown} copied={copied} url={downloadUrl} name={`${baseName(file.name)}.md`} onBack={clearResult} onReset={reset}/>:<><div className="markdown-selection"><span>{selected.size} of {pages.length} pages selected</span><div><button type="button" onClick={()=>setSelected(new Set(pages.map(page=>page.index)))}>Select all</button><button type="button" onClick={()=>setSelected(new Set())}>Clear</button></div></div><div className="markdown-pages">{pages.map(page=><button type="button" className={selected.has(page.index)?"selected":""} key={page.index} onClick={()=>toggle(page.index)}><span>Page {page.index}</span><img src={page.image} alt={`Page ${page.index}`}/><i>{selected.has(page.index)?<Check size={14}/>:null}</i><small>{page.text.trim()?`${page.text.trim().split(/\s+/).length} words`:"Scanned / no text"}</small></button>)}</div></>}
    </main>{!markdown?<aside className="markdown-panel"><div><span className="auto-print-kicker">RepetiGo converter</span><h2>PDF to Markdown</h2><p>Create reusable Markdown for documentation, websites and AI workflows.</p></div><section className="markdown-settings"><h3>Conversion settings</h3><label><input type="checkbox" checked={detectHeadings} onChange={event=>setDetectHeadings(event.target.checked)}/> Detect headings by font size</label><label><input type="checkbox" checked={preserveLinks} onChange={event=>setPreserveLinks(event.target.checked)}/> Detect visible web links</label><label><input type="checkbox" checked={includePageBreaks} onChange={event=>setIncludePageBreaks(event.target.checked)}/> Add page separators</label></section><div className="markdown-ready"><FileSearch size={18}/><div><strong>{selected.size?"Ready to convert":"Select at least one page"}</strong><small>{pages.filter(page=>selected.has(page.index)&&!page.text.trim()).length} selected pages may require OCR.</small></div></div>{processing?<div className="markdown-progress"><span>Converting… {progress}%</span><progress value={progress} max="100"/></div>:null}<button className="markdown-submit" type="button" disabled={!selected.size||processing||!pages.some(page=>selected.has(page.index)&&page.text.trim())} onClick={convert}>{processing?<LoaderCircle className="spin" size={18}/>:<FileCode2 size={18}/>} {processing?"Creating Markdown…":"Convert to Markdown"}</button><button className="markdown-reset" type="button" onClick={reset}><RotateCcw size={15}/> Start over</button></aside>:<ToolPromotionRail context="pdf-to-markdown-result"/>}</div>{error?<div className="profile-alert error markdown-error">{error}{!pages.some(page=>page.text.trim())?<Link href="/pdf-tools/ocr-pdf">Open OCR PDF</Link>:null}</div>:null}</div>;
}
function MarkdownResult({markdown,setMarkdown,preview,setPreview,copy,copied,url,name,onBack,onReset}:{markdown:string;setMarkdown(v:string):void;preview:"source"|"preview";setPreview(v:"source"|"preview"):void;copy():void;copied:boolean;url:string;name:string;onBack():void;onReset():void}){return <section className="markdown-result"><div className="markdown-result-head"><div><span><Check size={20}/></span><div><h2>Markdown is ready</h2><p>Edit, preview, copy or download the result.</p></div></div><div><button className={preview==="source"?"active":""} type="button" onClick={()=>setPreview("source")}><FileCode2 size={15}/> Source</button><button className={preview==="preview"?"active":""} type="button" onClick={()=>setPreview("preview")}><Eye size={15}/> Preview</button></div></div>{preview==="source"?<textarea value={markdown} onChange={event=>setMarkdown(event.target.value)} spellCheck={false}/>:<article className="markdown-rendered">{renderMarkdown(markdown)}</article>}<div className="markdown-result-actions"><button type="button" onClick={copy}><Clipboard size={17}/>{copied?"Copied!":"Copy Markdown"}</button><a href={url} download={name}><Download size={18}/> Download .md</a></div><footer><button type="button" onClick={onBack}>Change page selection</button><button type="button" onClick={onReset}>Convert another PDF</button></footer><RelatedToolSuggestions context="pdf-to-markdown-result"/></section>}

async function extractPages(file:File){const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/legacy/build/pdf.worker.min.mjs",import.meta.url).toString();const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;const output:PageData[]=[];for(let number=1;number<=pdf.numPages;number++){const page=await pdf.getPage(number),base=page.getViewport({scale:1}),view=page.getViewport({scale:Math.min(.7,170/base.width)}),canvas=document.createElement("canvas");canvas.width=Math.ceil(view.width);canvas.height=Math.ceil(view.height);const context=canvas.getContext("2d");if(!context)throw new Error("Canvas unavailable");await page.render({canvas,canvasContext:context,viewport:view}).promise;const content=await page.getTextContent(),items=content.items as Array<{str?:string;transform?:number[];fontName?:string;width?:number}>;const grouped=new Map<number,TextLine[]>();for(const item of items){if(!item.str?.trim()||!item.transform)continue;const y=Math.round(item.transform[5]/3)*3,line:TextLine={text:item.str,fontSize:Math.abs(item.transform[0])||10,bold:/bold|black|heavy/i.test(item.fontName||""),x:item.transform[4],y:item.transform[5]};grouped.set(y,[...(grouped.get(y)||[]),line]);}const lines=Array.from(grouped.values()).sort((a,b)=>(b[0]?.y||0)-(a[0]?.y||0)).map(parts=>{const sorted=parts.sort((a,b)=>a.x-b.x);return{text:sorted.map(part=>part.text).join(" ").replace(/\s+/g," ").trim(),fontSize:Math.max(...sorted.map(part=>part.fontSize)),bold:sorted.some(part=>part.bold),x:sorted[0]?.x||0,y:sorted[0]?.y||0};});output.push({index:number,image:canvas.toDataURL("image/jpeg",.8),lines,text:lines.map(line=>line.text).join("\n")});}return output;}
function pageToMarkdown(page:PageData,options:{detectHeadings:boolean;preserveLinks:boolean}){if(!page.lines.length)return "";const sizes=page.lines.map(line=>line.fontSize).sort((a,b)=>a-b),body=sizes[Math.floor(sizes.length*.55)]||10,max=Math.max(...sizes);const lines:string[]=[];for(const line of page.lines){let text=cleanText(line.text);if(!text)continue;if(options.preserveLinks)text=text.replace(/(?<!\]\()(https?:\/\/[^\s)]+)/g,"[$1]($1)");if(/^([•·▪◦]|[-–—])\s*/.test(text))text=`- ${text.replace(/^([•·▪◦]|[-–—])\s*/,"")}`;else if(/^\d+[.)]\s+/.test(text))text=text.replace(/^(\d+)[.)]\s+/,"$1. ");else if(options.detectHeadings&&line.fontSize>=Math.max(body*1.45,max*.8)&&text.length<130)text=`# ${text}`;else if(options.detectHeadings&&(line.bold||line.fontSize>=body*1.18)&&text.length<150)text=`## ${text}`;lines.push(text);}return normalizeMarkdown(lines.join("\n\n"));}
function cleanText(value:string){return value.replace(/\u00ad/g,"").replace(/\s+/g," ").trim();}function normalizeMarkdown(value:string){return value.replace(/\n{3,}/g,"\n\n").replace(/([^\n])-\n\n([a-z])/g,"$1$2").trim();}function renderMarkdown(markdown:string){return markdown.split(/\n/).map((line,index)=>{if(line.startsWith("### "))return <h3 key={index}>{line.slice(4)}</h3>;if(line.startsWith("## "))return <h2 key={index}>{line.slice(3)}</h2>;if(line.startsWith("# "))return <h1 key={index}>{line.slice(2)}</h1>;if(line==="---")return <hr key={index}/>;if(line.startsWith("- "))return <li key={index}>{line.slice(2)}</li>;if(/^\d+\. /.test(line))return <li key={index}>{line.replace(/^\d+\. /,"")}</li>;if(!line)return <br key={index}/>;return <p key={index}>{line}</p>});}function baseName(name:string){return name.replace(/\.pdf$/i,"");}function formatBytes(bytes:number){return bytes<1048576?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/1048576).toFixed(2)} MB`;}
