"use client";

import { useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { AlignCenter, Bold, Download, ImagePlus, Italic, Plus, ShieldCheck, Trash2, Type, Underline } from "lucide-react";
import { DashboardShell } from "../../DashboardShell";
import { PdfToolUpload } from "../../pdf-tools/PdfToolUpload";
import "./watermark.css";
import "../image-preview-fixes.css";

type Layer={id:number;kind:"text"|"image";x:number;y:number;scale:number;rotation:number;opacity:number;text?:string;src?:string;font?:string;size?:number;color?:string;bold?:boolean;italic?:boolean;underline?:boolean};
type Photo={file:File;url:string;width:number;height:number};

export default function WatermarkImagePage(){
  const baseInput=useRef<HTMLInputElement>(null),markInput=useRef<HTMLInputElement>(null),stage=useRef<HTMLDivElement>(null),nextId=useRef(1),drag=useRef<{id:number,x:number,y:number,left:number,top:number}|null>(null);
  const[photo,setPhoto]=useState<Photo|null>(null),[layers,setLayers]=useState<Layer[]>([]),[selected,setSelected]=useState<number|null>(null),[format,setFormat]=useState<"png"|"jpeg">("png"),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const active=layers.find(layer=>layer.id===selected)||null;
  async function upload(files:FileList){const file=files[0];if(!file)return;clear();try{const url=URL.createObjectURL(file),image=await load(url);setPhoto({file,url,width:image.naturalWidth,height:image.naturalHeight});}catch{setError("This image could not be opened.");}}
  function clear(){if(photo)URL.revokeObjectURL(photo.url);layers.forEach(layer=>{if(layer.src)URL.revokeObjectURL(layer.src);});setPhoto(null);setLayers([]);setSelected(null);setError("");}
  function addText(){const layer:Layer={id:nextId.current++,kind:"text",x:50,y:18,scale:1,rotation:0,opacity:100,text:"Write your text here",font:"Arial",size:48,color:"#ffffff",bold:false,italic:false,underline:false};setLayers(value=>[...value,layer]);setSelected(layer.id);}
  function addImage(files:FileList){const file=files[0];if(!file)return;const src=URL.createObjectURL(file),layer:Layer={id:nextId.current++,kind:"image",x:50,y:50,scale:.3,rotation:0,opacity:80,src};setLayers(value=>[...value,layer]);setSelected(layer.id);}
  function change(values:Partial<Layer>){if(selected===null)return;setLayers(list=>list.map(layer=>layer.id===selected?{...layer,...values}:layer));}
  function remove(){if(selected===null)return;const found=layers.find(layer=>layer.id===selected);if(found?.src)URL.revokeObjectURL(found.src);setLayers(list=>list.filter(layer=>layer.id!==selected));setSelected(null);}
  function startDrag(event:ReactPointerEvent,id:number){const layer=layers.find(value=>value.id===id);if(!layer)return;event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);drag.current={id,x:event.clientX,y:event.clientY,left:layer.x,top:layer.y};setSelected(id);}
  function moveDrag(event:ReactPointerEvent){if(!drag.current||!stage.current)return;const box=stage.current.getBoundingClientRect(),d=drag.current;changeLayer(d.id,{x:clamp(d.left+(event.clientX-d.x)/box.width*100,0,100),y:clamp(d.top+(event.clientY-d.y)/box.height*100,0,100)});}
  async function download(){if(!photo||busy)return;setBusy(true);setError("");try{const base=await load(photo.url),canvas=document.createElement("canvas");canvas.width=photo.width;canvas.height=photo.height;const ctx=canvas.getContext("2d");if(!ctx)throw new Error();ctx.drawImage(base,0,0);for(const layer of layers){ctx.save();ctx.globalAlpha=layer.opacity/100;ctx.translate(layer.x/100*canvas.width,layer.y/100*canvas.height);ctx.rotate(layer.rotation*Math.PI/180);if(layer.kind==="text"){const size=(layer.size||48)*canvas.width/1200;ctx.font=`${layer.italic?"italic ":""}${layer.bold?"700 ":"400 "}${size}px ${layer.font||"Arial"}`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillStyle=layer.color||"#fff";ctx.fillText(layer.text||"",0,0);if(layer.underline){const width=ctx.measureText(layer.text||"").width;ctx.fillRect(-width/2,size*.58,width,Math.max(2,size*.05));}}else if(layer.src){const mark=await load(layer.src),width=canvas.width*layer.scale,height=width*mark.naturalHeight/mark.naturalWidth;ctx.drawImage(mark,-width/2,-height/2,width,height);}ctx.restore();}const blob=await canvasBlob(canvas,`image/${format}`,format==="jpeg"?.92:1),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${photo.file.name.replace(/\.[^.]+$/,"")}-watermarked.${format==="jpeg"?"jpg":"png"}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError("Watermarked image could not be exported.");}finally{setBusy(false);}}
  if(!photo)return <DashboardShell activePath="/image-tools"><div className="dashboard image-transform-shell"><PdfToolUpload title="Watermark Image" description="Add custom text or logo watermarks to JPG, PNG, and WebP images." icon={ImagePlus} inputRef={baseInput} onFiles={upload} accept="image/jpeg,image/png,image/webp" multiple={false} buttonLabel="Select image" dropLabel="or drop an image here"/>{error?<p className="image-transform-error">{error}</p>:null}</div></DashboardShell>;
  return <DashboardShell activePath="/image-tools"><div className="dashboard watermark-page"><input ref={baseInput} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{if(e.target.files)void upload(e.target.files);e.target.value="";}}/><input ref={markInput} hidden type="file" accept="image/*" onChange={e=>{if(e.target.files)addImage(e.target.files);e.target.value="";}}/>
    <div className="compress-heading"><div><span className="auto-print-kicker">Free Image Tool</span><h1>Watermark Image</h1><p>Add movable text and logo watermarks while keeping the full image visible.</p></div><span><ShieldCheck size={16}/> Files stay in your browser</span></div>
    <div className="watermark-layout"><main><header><div><strong>{photo.file.name}</strong><small>{photo.width} x {photo.height}</small></div><button onClick={()=>baseInput.current?.click()}>Replace image</button></header>
      <div className="watermark-toolbar"><select aria-label="Font" value={active?.font||"Arial"} disabled={active?.kind!=="text"} onChange={e=>change({font:e.target.value})}><option>Arial</option><option>Georgia</option><option>Verdana</option><option>Impact</option><option>Courier New</option></select><input aria-label="Text size" type="number" min="12" max="180" value={active?.size||48} disabled={active?.kind!=="text"} onChange={e=>change({size:Number(e.target.value)})}/><button className={active?.bold?"active":""} disabled={active?.kind!=="text"} onClick={()=>change({bold:!active?.bold})}><Bold size={17}/></button><button className={active?.italic?"active":""} disabled={active?.kind!=="text"} onClick={()=>change({italic:!active?.italic})}><Italic size={17}/></button><button className={active?.underline?"active":""} disabled={active?.kind!=="text"} onClick={()=>change({underline:!active?.underline})}><Underline size={17}/></button><input aria-label="Text color" type="color" value={active?.color||"#ffffff"} disabled={active?.kind!=="text"} onChange={e=>change({color:e.target.value})}/><AlignCenter size={18}/><button disabled={!active} onClick={remove}><Trash2 size={17}/></button></div>
      <div className="watermark-workspace"><div ref={stage} className={`watermark-stage ${photo.height>photo.width?"portrait":"landscape"}`} style={{aspectRatio:`${photo.width}/${photo.height}`,backgroundImage:`url(${JSON.stringify(photo.url)})`}} onPointerMove={moveDrag} onPointerUp={()=>drag.current=null}>{layers.map(layer=><div key={layer.id} className={`watermark-layer ${layer.kind} ${selected===layer.id?"selected":""}`} style={{left:`${layer.x}%`,top:`${layer.y}%`,width:layer.kind==="image"?`${layer.scale*100}%`:undefined,opacity:layer.opacity/100,transform:`translate(-50%,-50%) rotate(${layer.rotation}deg) scale(${layer.kind==="text"?layer.scale:1})`,fontFamily:layer.font,fontSize:`${layer.size||48}px`,fontWeight:layer.bold?700:400,fontStyle:layer.italic?"italic":"normal",textDecoration:layer.underline?"underline":"none",color:layer.color}} onPointerDown={e=>startDrag(e,layer.id)}>{layer.kind==="text"?layer.text:<img src={layer.src} alt="Watermark"/>}</div>)}</div></div>
      <footer><button className="watermark-remove" onClick={clear}><Trash2 size={17}/> Remove image</button><button className="watermark-download" disabled={busy} onClick={()=>void download()}><Download size={18}/> {busy?"Exporting...":"Download watermarked image"}</button></footer></main>
      <aside><div className="image-transform-side-title"><span><ImagePlus size={20}/></span><div><small>RepetiGo Image Tools</small><h2>Watermark images</h2></div></div><div className="watermark-add-buttons"><button onClick={()=>markInput.current?.click()}><ImagePlus size={19}/> Add image</button><button onClick={addText}><Type size={19}/> Add text</button></div>{active?<div className="watermark-controls">{active.kind==="text"?<label><span>Watermark text</span><textarea value={active.text} onChange={e=>change({text:e.target.value})}/></label>:null}<label><span>Size <b>{Math.round(active.scale*100)}%</b></span><input type="range" min="10" max={active.kind==="text"?250:100} value={active.scale*100} onChange={e=>change({scale:Number(e.target.value)/100})}/></label><label><span>Opacity <b>{active.opacity}%</b></span><input type="range" min="5" max="100" value={active.opacity} onChange={e=>change({opacity:Number(e.target.value)})}/></label><label><span>Rotation <b>{active.rotation}°</b></span><input type="range" min="-180" max="180" value={active.rotation} onChange={e=>change({rotation:Number(e.target.value)})}/></label><button className="watermark-delete-layer" onClick={remove}><Trash2 size={16}/> Delete selected watermark</button></div>:<p className="watermark-hint">Add text or a logo, then drag it directly on the image.</p>}<label className="watermark-format"><span>Download format</span><select value={format} onChange={e=>setFormat(e.target.value as "png"|"jpeg")}><option value="png">PNG</option><option value="jpeg">JPG</option></select></label><button className="image-transform-run" disabled={busy} onClick={()=>void download()}><Download size={18}/> Watermark image</button></aside></div>{error?<p className="image-transform-error">{error}</p>:null}
  </div></DashboardShell>;
  function changeLayer(id:number,values:Partial<Layer>){setLayers(list=>list.map(layer=>layer.id===id?{...layer,...values}:layer));}
}

function load(url:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=url;});}
function canvasBlob(canvas:HTMLCanvasElement,type:string,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error()),type,quality));}
function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value));}
