# Generated by Django 6.0.6 on 2026-07-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        # attire_category already exists on the live database (added out of band
        # before this migration was written) - only update Django's model state,
        # do not attempt to add the column again.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='printorder',
                    name='attire_category',
                    field=models.CharField(blank=True, default='', max_length=40),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='printorder',
            name='gemini_photo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
