# Generated by Django 5.1.4 on 2026-07-29 18:54

from decimal import Decimal

from django.db import migrations, models


def seed_wallet_settings_and_tool_pricing(apps, schema_editor):
    WalletSetting = apps.get_model("api", "WalletSetting")
    ToolPricing = apps.get_model("api", "ToolPricing")

    wallet_settings = [
        ("signup_bonus", "Signup Bonus", Decimal("10.00"), "Rs. credited to a new shop's wallet once their email is verified. Matches the amount advertised on the Pricing page."),
        ("referral_bonus", "Referral Bonus", Decimal("0.00"), "Rs. credited for a successful referral. Set is_active=True and a value once the referral programme launches."),
        ("credit_limit", "Wallet Grace Limit", Decimal("-50.00"), "Lowest balance a wallet is allowed to reach before paid tools are blocked and topup is required."),
        ("daily_grace_limit", "Daily Grace Usage Limit", Decimal("5.00"), "Max Rs. that can be spent per calendar day while the wallet balance is at or below zero."),
    ]
    for key, label, value, description in wallet_settings:
        WalletSetting.objects.get_or_create(
            key=key,
            defaults={"label": label, "value": value, "description": description, "is_active": key != "referral_bonus"},
        )

    tool_prices = [
        ("print_bw_page", "PrintPilot - Black & White Page", "per page", Decimal("0.50"), True),
        ("print_color_page", "PrintPilot - Color Page", "per page", Decimal("1.00"), True),
        ("passport_photo", "Passport / ID Photo", "per request", Decimal("5.00"), True),
    ]
    for tool_key, label, unit, price, is_billable in tool_prices:
        ToolPricing.objects.get_or_create(
            tool_key=tool_key,
            defaults={"label": label, "unit": unit, "price": price, "is_billable": is_billable},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_key', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('unit', models.CharField(blank=True, default='per use', max_length=80)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_billable', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tool_key'],
            },
        ),
        migrations.CreateModel(
            name='WalletSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='tool_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(seed_wallet_settings_and_tool_pricing, noop_reverse),
    ]
