# Generated by Django 6.0.6 on 2026-08-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_toolpricing_walletsetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='document',
            field=models.FileField(blank=True, upload_to='print_orders/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='gemini_photo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='original_filename',
            field=models.TextField(blank=True),
        ),
    ]
