# Generated by Django 5.1.4 on 2026-07-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_toolpricing_walletsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('name', models.CharField(max_length=255, unique=True)),
                ('extracted_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['extracted_status'], name='api_googlep_extract_4d6ab4_idx')],
            },
        ),
    ]
