# Generated by Django 6.0.6 on 2026-07-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_create_passportphotojob_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportphotojob',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
