# Generated by Django 5.1.4 on 2026-07-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_googleplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleplace',
            name='extractedby',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
