# Generated by Django 5.1.4 on 2026-06-21 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_printorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='token_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='printorder',
            name='token_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='printorder',
            index=models.Index(fields=['user', 'token_number'], name='api_printor_user_id_2ab5a9_idx'),
        ),
    ]
