# Generated by Django 5.1.4 on 2026-07-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_passportphotojob_prompt_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportphotojob',
            name='price_item_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='passportphotojob',
            name='price_label',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='passportphotojob',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
