# Generated by Django 5.1.4 on 2026-07-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_passportphotojob_price_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportphotojob',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passport_photo_jobs', to='api.printorder'),
        ),
    ]
