# Generated by Django 5.1.4 on 2026-07-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_googleplacedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleplacedetail',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='googleplacedetail',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('follow_up', 'Follow-up'), ('discussion', 'In Discussion'), ('interested', 'Interested'), ('call_discussed', 'Call Discussed'), ('converted', 'Converted'), ('not_interested', 'Not Interested')], default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='googleplacedetail',
            index=models.Index(fields=['status'], name='api_googlep_status_875389_idx'),
        ),
    ]
