# Generated by Django 5.1.4 on 2026-07-31 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_googleplacedetail_notes_googleplacedetail_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status_change', 'Status change'), ('note', 'Note')], max_length=20)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='googleplacedetail',
            name='next_follow_up_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='googleplacedetail',
            index=models.Index(fields=['next_follow_up_at'], name='api_googlep_next_fo_5a1dba_idx'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.googleplacedetail'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', 'created_at'], name='api_leadact_lead_id_e9a160_idx'),
        ),
    ]
