# Generated by Django 6.0.6 on 2026-08-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_printorder_document_and_more'),
        ('api', '0007_leadactivity_googleplacedetail_next_follow_up_at_and_more'),
    ]

    operations = [
    ]
