# Generated by Django 5.1.4 on 2026-08-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_toolpricing_price_b2b_toolpricing_price_b2c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cash_counter_permitted',
            field=models.BooleanField(default=True),
        ),
    ]
