# Generated by Django 6.0.6 on 2026-07-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_contactmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='api_contact_created_e89a17_idx',
            old_name='api_contact_created_9c3435_idx',
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='api_wallett_user_id_d72a94_idx',
            old_name='api_wallet_user_id_742aaa_idx',
        ),
    ]
