# Generated by Django 5.1.4 on 2026-08-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_agent_shopprofile_referred_by_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
