# Generated by Django 5.1.4 on 2026-08-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_contactmessage_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agent_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
