# Generated by Django 5.1.4 on 2026-08-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userprofile_agent_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
