# Generated by Django 5.1.4 on 2026-08-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_seed_biodata_maker_tool_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_key', models.CharField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
