# Generated by Django 5.1.4 on 2026-08-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_seed_tool_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
