# Generated by Django 5.1.4 on 2026-08-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_googleplacedetail_linked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='admin_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printorder',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
