# Generated by Django 5.1.4 on 2026-09-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_upiqrrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('backup', 'Backup - only if the agent and Gemini fallback both fail'), ('primary', 'Primary - generate with OpenAI immediately on upload')], default='backup', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
