# Generated by Django 5.1.4 on 2026-09-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_passportaiconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportaiconfig',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='passportaiconfig',
            name='mode',
            field=models.CharField(choices=[('agent_gemini_backup', 'Agent first, Gemini backup - only if the agent fails'), ('agent_openai_backup', 'Agent first, OpenAI backup - only if the agent fails'), ('openai_primary', 'OpenAI primary - generate with OpenAI immediately on upload'), ('gemini_primary', 'Gemini primary - generate with Gemini immediately on upload')], default='agent_gemini_backup', max_length=30),
        ),
    ]
