# Generated by Django 5.1.4 on 2026-09-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_passportaiconfig_enabled_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GooglePlace',
        ),
        migrations.RemoveField(
            model_name='googleplacedetail',
            name='linked_user',
        ),
        migrations.RemoveField(
            model_name='googleplacedetail',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='leadactivity',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='scraperun',
            name='started_by',
        ),
        migrations.DeleteModel(
            name='LeadTag',
        ),
        migrations.DeleteModel(
            name='GooglePlaceDetail',
        ),
        migrations.DeleteModel(
            name='LeadActivity',
        ),
        migrations.DeleteModel(
            name='ScrapeRun',
        ),
    ]
