# Generated by Django 5.1.4 on 2026-09-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_delete_googleplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
                ('division', models.CharField(max_length=120)),
                ('pincode', models.CharField(max_length=10)),
                ('sno', models.CharField(blank=True, default='', max_length=10)),
                ('agent_id', models.CharField(blank=True, default='', max_length=40)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'division'], name='api_leadage_state_6f5779_idx'), models.Index(fields=['state', 'division', 'pincode'], name='api_leadage_state_07984d_idx')],
            },
        ),
    ]
