# Generated by Django 5.1.4 on 2026-09-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_leadagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='leadagent',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='agents', to='api.leadtag'),
        ),
    ]
