# Generated by Django 5.1.4 on 2026-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_seed_id_card_maker_tool_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agent_ws_connected',
            field=models.BooleanField(default=False),
        ),
    ]
