# Generated by Django 6.0.6 on 2026-09-29 22:14

from django.db import migrations, models


# Failover order for the GPT Pooler laptops - priority 1 pulls jobs first,
# 2 takes over when 1 is offline/full, then 3. Editable later from the
# admin API (admin/gpt-pooler/nodes/) or Django admin.
SEEDED_POOLER_NODES = [
    ("repetigo.official@gmail.com", 1),
    ("sk6201184579@gmail.com", 2),
    ("cmfankit1@gmail.com", 3),
]


def seed_pooler_nodes(apps, schema_editor):
    PoolerNode = apps.get_model("api", "PoolerNode")
    for email, priority in SEEDED_POOLER_NODES:
        PoolerNode.objects.update_or_create(email=email, defaults={"priority": priority, "is_enabled": True})


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_userprofile_agent_ws_connected'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('machine_name', models.CharField(blank=True, default='', max_length=120)),
                ('total_workers', models.PositiveIntegerField(default=0)),
                ('free_workers', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('jobs_completed', models.PositiveIntegerField(default=0)),
                ('last_job_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='printorder',
            name='photo_claimed_by_email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.RunPython(seed_pooler_nodes, noop_reverse),
    ]
