# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_userprofile_agent_ws_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='family_photo_inputs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
