# Generated by Django 5.1.4 on 2026-10-03 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_blogarticle_tags_focus_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='auto_caption_images',
            field=models.BooleanField(default=False, help_text="Show each image's alt text as a caption"),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='cover_image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='lazy_load_images',
            field=models.BooleanField(default=False, help_text='Add loading=lazy to images in the article body'),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='require_image_alt',
            field=models.BooleanField(default=True, help_text='Admin: block publishing while an image has no alt text'),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='template',
            field=models.CharField(choices=[('default', 'Default template'), ('wide', 'Wide template')], default='default', max_length=12),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('trash', 'Trash')], default='draft', max_length=12),
        ),
        migrations.CreateModel(
            name='BlogRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.CharField(blank=True, max_length=320)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='api.blogarticle')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
