# Generated by Django 6.0.6 on 2026-10-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_pooler_node'),
        ('api', '0054_blog_editor_sidebar_fields'),
    ]

    operations = [
    ]
