# Generated by Django 5.1.4 on 2026-10-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_phone_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
