# Generated by Django 6.0.6 on 2026-10-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_printorder_profile_name'),
        ('api', '0055_merge_20261007_0942'),
    ]

    operations = [
    ]
