# Generated by Django 5.1.4 on 2026-10-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_printorder_profile_name'),
        ('api', '0055_merge_20261007_0942'),
        ('api', '0056_widen_phone_fields'),
    ]

    operations = [
    ]
