"use client";

import { useEffect, useRef, useState, type PointerEvent } from "react";
import { Crop, Download, FileCode2, Image as ImageIcon, LoaderCircle, RotateCw, Scaling, ShieldCheck, WandSparkles } from "lucide-react";
import { PdfToolUpload } from "../pdf-tools/PdfToolUpload";

export type ImageTransformSlug = "image-converter" | "resize-image" | "crop-image" | "rotate-image" | "convert-to-jpg" | "convert-from-jpg" | "html-to-image";
const configs = {
  "image-converter": { title: "Image Converter", description: "Convert images into JPG, PNG, WebP, SVG, BMP, ICO, or PDF.", icon: WandSparkles, accept: "image/*,.svg", button: "Select images" },
  "resize-image": { title: "Resize Image", description: "Resize images by percentage or exact pixel dimensions.", icon: Scaling, accept: "image/jpeg,image/png,image/webp", button: "Select images" },
  "crop-image": { title: "Crop Image", description: "Crop images to square, portrait, landscape, or custom ratios.", icon: Crop, accept: "image/jpeg,image/png,image/webp", button: "Select images" },
  "rotate-image": { title: "Rotate Image", description: "Rotate JPG, PNG, and WebP images with one click.", icon: RotateCw, accept: "image/jpeg,image/png,image/webp", button: "Select images" },
  "convert-to-jpg": { title: "Convert to JPG", description: "Convert PNG, WebP, SVG, and GIF images into compact JPG files.", icon: ImageIcon, accept: "image/png,image/webp,image/jpeg,image/svg+xml,image/gif,.png,.webp,.jpg,.jpeg,.svg,.gif,.heic,.heif", button: "Select images" },
  "convert-from-jpg": { title: "Image Format Converter", description: "Convert JPG and WebP images into PNG or WebP files.", icon: WandSparkles, accept: "image/jpeg,image/webp,.jpg,.jpeg,.webp", button: "Select JPG or WebP images" },
  "html-to-image": { title: "HTML to Image", description: "Render readable HTML content into a downloadable image.", icon: FileCode2, accept: ".html,.htm,text/html", button: "Select HTML files" },
} as const;

type Item = { file: File; sourceUrl: string; width: number; height: number };
type Result = { blob: Blob; url: string; name: string; width: number; height: number };
type ResizeMode = "size" | "percentage" | "social";
type CropRect = { x: number; y: number; width: number; height: number };
type ReactPointerEvent<T = HTMLElement> = PointerEvent<HTMLElement>;

export function isImageTransformSlug(value: string): value is ImageTransformSlug { return value in configs; }

export default function ImageTransformTool({ slug }: { slug: ImageTransformSlug }) {
  const config = configs[slug]; const inputRef = useRef<HTMLInputElement>(null); const rotationRequest = useRef(0); const [item, setItem] = useState<Item | null>(null); const [result, setResult] = useState<Result | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [percent, setPercent] = useState(75); const [width, setWidth] = useState(1200); const [height, setHeight] = useState(800); const [resizeMode, setResizeMode] = useState<ResizeMode>("size"); const [socialPreset, setSocialPreset] = useState("instagram-post"); const [targetKB, setTargetKB] = useState(0); const [lockRatio, setLockRatio] = useState(true); const [ratio, setRatio] = useState("FreeForm"); const [cropRect, setCropRect] = useState<CropRect>({x:0,y:0,width:1200,height:800}); const [angle, setAngle] = useState(0); const [straighten, setStraighten] = useState(0); const [rotationTarget, setRotationTarget] = useState<"all"|"portrait"|"landscape">("all"); const [output, setOutput] = useState<"png" | "webp">("png"); const [converterOutput, setConverterOutput] = useState<"jpg"|"png"|"webp"|"svg"|"bmp"|"ico"|"pdf">("jpg"); const [converterResize, setConverterResize] = useState("original"); const [autoOrient, setAutoOrient] = useState(true); const [stripMetadata, setStripMetadata] = useState(true); const [quality, setQuality] = useState(90);

  async function add(files: FileList) { const file = files[0]; if (!file) return; clear(); setError(""); try { if (slug === "html-to-image") { setBusy(true); const sourceUrl = URL.createObjectURL(file); setItem({ file, sourceUrl, width: 1200, height: 800 }); const made=await htmlToImage(file); setResult({...made,url:URL.createObjectURL(made.blob)}); setBusy(false); return; } const sourceUrl = URL.createObjectURL(file); const dimensions = await readDimensions(sourceUrl); setItem({ file, sourceUrl, ...dimensions }); setWidth(dimensions.width); setHeight(dimensions.height); setCropRect({x:0,y:0,width:dimensions.width,height:dimensions.height}); } catch { setBusy(false); setError("This file could not be opened or rendered."); } }
  function clear() { if (item) URL.revokeObjectURL(item.sourceUrl); if (result) URL.revokeObjectURL(result.url); setItem(null); setResult(null); }
  async function process() { if (!item || busy) return; setBusy(true); setError(""); if (result) URL.revokeObjectURL(result.url); try { const made = slug === "html-to-image" ? await htmlToImage(item.file) : slug === "image-converter" ? await universalConvert(item,{output:converterOutput,resize:converterResize,quality}) : await transformImage(item, slug, { percent, width, height, resizeMode, socialPreset, targetKB, lockRatio, ratio, cropRect, angle, straighten, rotationTarget, output, quality }); setResult({ ...made, url: URL.createObjectURL(made.blob) }); } catch { setError("The image could not be processed with these settings."); } finally { setBusy(false); } }
  useEffect(() => { if (slug !== "rotate-image" || !item) return; const requestId=++rotationRequest.current; const timer=window.setTimeout(async()=>{setBusy(true);setError("");try{const made=await transformImage(item,"rotate-image",{percent,width,height,resizeMode,socialPreset,targetKB,lockRatio,ratio,cropRect,angle,straighten,rotationTarget,output,quality});if(requestId!==rotationRequest.current)return;const url=URL.createObjectURL(made.blob);setResult(current=>{if(current)URL.revokeObjectURL(current.url);return{...made,url};});}catch{if(requestId===rotationRequest.current)setError("The image could not be rotated with these settings.");}finally{if(requestId===rotationRequest.current)setBusy(false);}},90);return()=>window.clearTimeout(timer);},[slug,item,angle,straighten,rotationTarget]);
  const Icon = config.icon;
  if (!item) return <><PdfToolUpload title={config.title} description={config.description} icon={Icon} inputRef={inputRef} onFiles={add} accept={config.accept} multiple={false} buttonLabel={config.button} dropLabel="or drop a compatible file here" />{error ? <p className="image-transform-error">{error}</p> : null}</>;

  return <div className="image-transform-page"><input ref={inputRef} hidden type="file" accept={config.accept} onChange={(event) => { if (event.target.files) void add(event.target.files); event.target.value = ""; }} />
    <div className="compress-heading"><div><span className="auto-print-kicker">Free Image Tool</span><h1>{config.title}</h1><p>{config.description}</p></div><span><ShieldCheck size={16} /> Files stay in your browser</span></div>
    <div className="image-transform-layout"><main><header><div><span><Icon size={21} /></span><div><strong>{item.file.name}</strong><small>{slug === "html-to-image" ? formatBytes(item.file.size) : `${item.width} × ${item.height} · ${formatBytes(item.file.size)}`}</small></div></div><button type="button" onClick={() => inputRef.current?.click()}>Replace file</button></header>{slug === "crop-image" && !result ? <CropEditor item={item} rect={cropRect} setRect={setCropRect} /> : <div aria-label={result ? "Processed image preview" : "Original image preview"} className={`image-transform-preview ${result || slug !== "html-to-image" ? "has-image" : ""}`} style={result || slug !== "html-to-image" ? { backgroundImage: `url(${JSON.stringify(result?.url || item.sourceUrl)})` } : undefined}>{!result && slug === "html-to-image" ? <div><FileCode2 size={45} /><strong>HTML preview will appear after rendering</strong></div> : null}</div>}{result ? <footer><span>{result.width} × {result.height} · {formatBytes(result.blob.size)}</span><a href={result.url} download={result.name}><Download size={17} /> Download {result.name.split(".").pop()?.toUpperCase()}</a></footer> : null}</main>
      <aside><div className="image-transform-side-title"><span><Icon size={20} /></span><div><small>RepetiGo Image Tools</small><h2>{config.title}</h2></div></div><ToolControls slug={slug} item={item} percent={percent} setPercent={setPercent} width={width} setWidth={setWidth} height={height} setHeight={setHeight} resizeMode={resizeMode} setResizeMode={setResizeMode} socialPreset={socialPreset} setSocialPreset={setSocialPreset} targetKB={targetKB} setTargetKB={setTargetKB} lockRatio={lockRatio} setLockRatio={setLockRatio} ratio={ratio} setRatio={setRatio} cropRect={cropRect} setCropRect={setCropRect} angle={angle} setAngle={setAngle} straighten={straighten} setStraighten={setStraighten} rotationTarget={rotationTarget} setRotationTarget={setRotationTarget} output={output} setOutput={setOutput} converterOutput={converterOutput} setConverterOutput={setConverterOutput} converterResize={converterResize} setConverterResize={setConverterResize} autoOrient={autoOrient} setAutoOrient={setAutoOrient} stripMetadata={stripMetadata} setStripMetadata={setStripMetadata} quality={quality} setQuality={setQuality} />{slug==="rotate-image"?<div className="rotate-live-status">{busy?<><LoaderCircle className="spin" size={17}/> Updating preview…</>:<><RotateCw size={17}/> Preview updates automatically</>}</div>:slug==="html-to-image"?<div className="rotate-live-status">{busy?<><LoaderCircle className="spin" size={17}/> Rendering HTML…</>:<><FileCode2 size={17}/> Rendered automatically</>}</div>:<button className="image-transform-run" type="button" disabled={busy} onClick={process}>{busy ? <LoaderCircle className="spin" size={18} /> : <Icon size={18} />} {busy ? "Processing…" : config.title}</button>}<button className="image-transform-reset" type="button" onClick={clear}>Start over</button></aside>
    </div>{error ? <p className="image-transform-error">{error}</p> : null}</div>;
}

function ToolControls(p: { slug: ImageTransformSlug; item: Item; percent: number; setPercent(v:number):void; width:number; setWidth(v:number):void; height:number; setHeight(v:number):void; resizeMode:ResizeMode; setResizeMode(v:ResizeMode):void; socialPreset:string; setSocialPreset(v:string):void; targetKB:number; setTargetKB(v:number):void; lockRatio:boolean; setLockRatio(v:boolean):void; ratio:string; setRatio(v:string):void; cropRect:CropRect; setCropRect(v:CropRect):void; angle:number; setAngle(v:number):void; straighten:number; setStraighten(v:number):void; rotationTarget:"all"|"portrait"|"landscape"; setRotationTarget(v:"all"|"portrait"|"landscape"):void; output:"png"|"webp"; setOutput(v:"png"|"webp"):void; converterOutput:"jpg"|"png"|"webp"|"svg"|"bmp"|"ico"|"pdf"; setConverterOutput(v:"jpg"|"png"|"webp"|"svg"|"bmp"|"ico"|"pdf"):void; converterResize:string; setConverterResize(v:string):void; autoOrient:boolean; setAutoOrient(v:boolean):void; stripMetadata:boolean; setStripMetadata(v:boolean):void; quality:number; setQuality(v:number):void }) {
  if (p.slug === "image-converter") return <ConverterControls {...p} />;
  if (p.slug === "resize-image") return <ResizeControls {...p} />;
  if (p.slug === "crop-image") return <CropControls {...p} />;
  if (p.slug === "rotate-image") return <RotateControls {...p} />;
  if (p.slug === "convert-from-jpg") return <div className="image-transform-controls"><label><span>Output format</span><select value={p.output} onChange={(e)=>p.setOutput(e.target.value as "png"|"webp")}><option value="png">PNG</option><option value="webp">WebP</option></select></label>{p.output==="webp"?<Quality value={p.quality} setValue={p.setQuality}/>:null}</div>;
  if (p.slug === "convert-to-jpg") return <div className="image-transform-controls"><Quality value={p.quality} setValue={p.setQuality}/><p>Transparent areas are filled with white.</p></div>;
  return <div className="image-transform-controls"><p>Scripts, remote resources, and tracking are not executed. Readable HTML content is rendered locally.</p></div>;
}
function ConverterControls(p: Parameters<typeof ToolControls>[0]) { return <div className="image-transform-controls converter-settings"><h3>Conversion Settings</h3><label><span>Select an Output</span><select value={p.converterOutput} onChange={e=>p.setConverterOutput(e.target.value as typeof p.converterOutput)}><option value="jpg">JPG / JPEG</option><option value="png">PNG</option><option value="webp">WebP</option><option value="svg">SVG</option><option value="bmp">BMP</option><option value="ico">ICO</option><option value="pdf">PDF</option></select></label><div className="converter-route"><b>{sourceFormat(p.item.file)}</b><span>→</span><strong>{p.converterOutput.toUpperCase()}</strong></div><h3>Advanced Options</h3><label><span>Resize Output Image</span><select value={p.converterResize} onChange={e=>p.setConverterResize(e.target.value)}><option value="original">Keep original size</option><option value="75">Resize to 75%</option><option value="50">Resize to 50%</option><option value="25">Resize to 25%</option><option value="1920">Maximum 1920px</option></select><small>Choose a method if you want to resize the output image.</small></label>{["jpg","webp"].includes(p.converterOutput)?<Quality value={p.quality} setValue={p.setQuality}/>:null}<label className="check"><input type="checkbox" checked={p.autoOrient} onChange={e=>p.setAutoOrient(e.target.checked)}/><span>Auto Orient</span></label><small>Correctly orient using browser-decoded image data.</small><label className="check"><input type="checkbox" checked={p.stripMetadata} onChange={e=>p.setStripMetadata(e.target.checked)}/><span>Strip Metadata</span></label><small>Canvas exports omit EXIF, profiles, and comments.</small></div>; }
function CropControls(p: Parameters<typeof ToolControls>[0]) { const clampRect=(next:CropRect)=>({x:Math.max(0,Math.min(p.item.width-1,next.x)),y:Math.max(0,Math.min(p.item.height-1,next.y)),width:Math.max(1,Math.min(p.item.width-Math.max(0,next.x),next.width)),height:Math.max(1,Math.min(p.item.height-Math.max(0,next.y),next.height))}); const update=(key:keyof CropRect,value:number)=>p.setCropRect(clampRect({...p.cropRect,[key]:Math.round(value)})); const ratioChange=(value:string)=>{p.setRatio(value);if(value==="FreeForm")return;const [rw,rh]=value.split(":").map(Number),target=rw/rh,current=p.item.width/p.item.height;let width=p.item.width,height=p.item.height;if(current>target)width=Math.round(height*target);else height=Math.round(width/target);p.setCropRect({x:Math.round((p.item.width-width)/2),y:Math.round((p.item.height-height)/2),width,height});}; return <div className="image-transform-controls crop-settings"><h3>Crop Rectangle</h3><div className="crop-field-grid"><label><span>Width</span><input type="number" min="1" max={p.item.width} value={p.cropRect.width} onChange={e=>update("width",Number(e.target.value))}/></label><label><span>Height</span><input type="number" min="1" max={p.item.height} value={p.cropRect.height} onChange={e=>update("height",Number(e.target.value))}/></label></div><label><span>Aspect Ratio</span><select value={p.ratio} onChange={e=>ratioChange(e.target.value)}><option>FreeForm</option><option>1:1</option><option>4:3</option><option>3:4</option><option>16:9</option><option>9:16</option></select></label><h3>Crop Position</h3><div className="crop-field-grid"><label><span>Position (Y)</span><input type="number" min="0" max={p.item.height-p.cropRect.height} value={p.cropRect.y} onChange={e=>update("y",Number(e.target.value))}/></label><label><span>Position (X)</span><input type="number" min="0" max={p.item.width-p.cropRect.width} value={p.cropRect.x} onChange={e=>update("x",Number(e.target.value))}/></label></div><button className="crop-reset" type="button" onClick={()=>{p.setRatio("FreeForm");p.setCropRect({x:0,y:0,width:p.item.width,height:p.item.height});}}>Reset</button></div>; }

function CropEditor({item,rect,setRect}:{item:Item;rect:CropRect;setRect(v:CropRect):void}) { const action=useRef<{type:string;clientX:number;clientY:number;rect:CropRect}|null>(null); const begin=(event:ReactPointerEvent<HTMLDivElement>,type:string)=>{event.preventDefault();event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);action.current={type,clientX:event.clientX,clientY:event.clientY,rect:{...rect}};}; const move=(event:ReactPointerEvent<HTMLDivElement>)=>{const current=action.current;if(!current)return;const stage=event.currentTarget.parentElement?.getBoundingClientRect();if(!stage)return;const dx=(event.clientX-current.clientX)/stage.width*item.width,dy=(event.clientY-current.clientY)/stage.height*item.height;let next={...current.rect};if(current.type==="move"){next.x+=dx;next.y+=dy;}else{if(current.type.includes("e"))next.width+=dx;if(current.type.includes("s"))next.height+=dy;if(current.type.includes("w")){next.x+=dx;next.width-=dx;}if(current.type.includes("n")){next.y+=dy;next.height-=dy;}}next.width=Math.max(24,Math.min(item.width,next.width));next.height=Math.max(24,Math.min(item.height,next.height));next.x=Math.max(0,Math.min(item.width-next.width,next.x));next.y=Math.max(0,Math.min(item.height-next.height,next.y));setRect({x:Math.round(next.x),y:Math.round(next.y),width:Math.round(next.width),height:Math.round(next.height)});}; return <div className="crop-editor"><div className="crop-image-stage" style={{aspectRatio:`${item.width}/${item.height}`,backgroundImage:`url(${JSON.stringify(item.sourceUrl)})`}}><div className="crop-shade"/><div className="crop-selection" style={{left:`${rect.x/item.width*100}%`,top:`${rect.y/item.height*100}%`,width:`${rect.width/item.width*100}%`,height:`${rect.height/item.height*100}%`}} onPointerDown={e=>begin(e,"move")} onPointerMove={move} onPointerUp={()=>action.current=null}>{["nw","n","ne","e","se","s","sw","w"].map(handle=><i className={`crop-handle ${handle}`} key={handle} onPointerDown={e=>begin(e,handle)} />)}<span/><b/></div></div></div>; }

function RotateControls(p: Parameters<typeof ToolControls>[0]) { const reset=()=>{p.setAngle(0);p.setStraighten(0);p.setRotationTarget("all");}; return <div className="image-transform-controls rotate-settings"><span>Select files to rotate:</span><div className="rotate-targets"><button className={p.rotationTarget==="all"?"active":""} type="button" onClick={()=>p.setRotationTarget("all")}><i className="all"/>All</button><button className={p.rotationTarget==="portrait"?"active":""} type="button" onClick={()=>p.setRotationTarget("portrait")}><i className="portrait"/>Portrait</button><button className={p.rotationTarget==="landscape"?"active":""} type="button" onClick={()=>p.setRotationTarget("landscape")}><i className="landscape"/>Landscape</button></div><div className="rotate-label"><strong>Rotation</strong><button type="button" onClick={reset}>Reset all</button></div><div className="rotate-direction"><button type="button" onClick={()=>p.setAngle((p.angle+90)%360)}><span><RotateCw size={19}/></span>RIGHT</button><button type="button" onClick={()=>p.setAngle((p.angle-90)%360)}><span><RotateCw size={19}/></span>LEFT</button></div><label className="straighten-control"><span>Straighten <strong>{p.straighten}°</strong></span><input type="range" min="-15" max="15" step="1" value={p.straighten} onChange={e=>p.setStraighten(Number(e.target.value))}/><small>Rotate image in any angle</small></label><p>Final rotation: {normalizeAngle(p.angle+p.straighten)}°. {p.rotationTarget!=="all"?`Applied when the image is ${p.rotationTarget}.`:"Applied to the selected image."}</p></div>; }

function ResizeControls(p: Parameters<typeof ToolControls>[0]) { const presets: Record<string,[number,number]>={"instagram-post":[1080,1080],"instagram-story":[1080,1920],"facebook-post":[1200,630],"linkedin-post":[1200,627],"youtube-thumbnail":[1280,720]}; const setPreset=(value:string)=>{p.setSocialPreset(value);const size=presets[value];p.setWidth(size[0]);p.setHeight(size[1]);}; const setWidth=(value:number)=>{p.setWidth(value);if(p.lockRatio)p.setHeight(Math.max(1,Math.round(value*p.item.height/p.item.width)));}; const setHeight=(value:number)=>{p.setHeight(value);if(p.lockRatio)p.setWidth(Math.max(1,Math.round(value*p.item.width/p.item.height)));}; return <div className="image-transform-controls resize-settings">
  <h3>Resize Settings</h3><div className="resize-mode-tabs"><button className={p.resizeMode==="size"?"active":""} type="button" onClick={()=>p.setResizeMode("size")}>By Size</button><button className={p.resizeMode==="percentage"?"active":""} type="button" onClick={()=>p.setResizeMode("percentage")}>As Percentage</button><button className={p.resizeMode==="social"?"active":""} type="button" onClick={()=>p.setResizeMode("social")}>Social Media</button></div>
  {p.resizeMode==="size"?<><div className="resize-dimension-grid"><label><span>Width</span><input type="number" min="1" max="10000" value={p.width} onChange={e=>setWidth(Number(e.target.value))}/></label><label><span>Height <em>px</em></span><input type="number" min="1" max="10000" value={p.height} onChange={e=>setHeight(Number(e.target.value))}/></label></div><label className="check"><input type="checkbox" checked={p.lockRatio} onChange={e=>p.setLockRatio(e.target.checked)}/> Lock Aspect Ratio</label></>:null}
  {p.resizeMode==="percentage"?<label><span>Scale <strong>{p.percent}%</strong></span><input type="range" min="10" max="200" step="5" value={p.percent} onChange={e=>p.setPercent(Number(e.target.value))}/><small>{Math.round(p.item.width*p.percent/100)} × {Math.round(p.item.height*p.percent/100)} px</small></label>:null}
  {p.resizeMode==="social"?<label><span>Social media preset</span><select value={p.socialPreset} onChange={e=>setPreset(e.target.value)}><option value="instagram-post">Instagram Post · 1080×1080</option><option value="instagram-story">Instagram Story · 1080×1920</option><option value="facebook-post">Facebook Post · 1200×630</option><option value="linkedin-post">LinkedIn Post · 1200×627</option><option value="youtube-thumbnail">YouTube Thumbnail · 1280×720</option></select></label>:null}
  <div className="resize-export-head"><h3>Export Settings</h3></div><label><span>Output format</span><select value={p.output} onChange={e=>p.setOutput(e.target.value as "png"|"webp")}><option value="webp">WebP · smaller</option><option value="png">PNG · lossless</option></select></label>{p.output==="webp"?<Quality value={p.quality} setValue={p.setQuality}/>:null}<label><span>Target File Size <em>optional</em></span><div className="resize-target-input"><input type="number" min="0" placeholder="No limit" value={p.targetKB||""} onChange={e=>p.setTargetKB(Number(e.target.value))}/><b>KB</b></div></label>
  </div>; }
function Quality({value,setValue}:{value:number;setValue(v:number):void}) { return <label><span>Image quality <strong>{value}%</strong></span><input type="range" min="40" max="100" value={value} onChange={(e)=>setValue(Number(e.target.value))}/></label>; }

async function transformImage(item: Item, slug: ImageTransformSlug, settings: {percent:number;width:number;height:number;resizeMode:ResizeMode;socialPreset:string;targetKB:number;lockRatio:boolean;ratio:string;cropRect:CropRect;angle:number;straighten:number;rotationTarget:"all"|"portrait"|"landscape";output:"png"|"webp";quality:number}) { const image=await loadImage(item.sourceUrl); let sx=0,sy=0,sw=item.width,sh=item.height,dw=item.width,dh=item.height;
  if(slug==="resize-image"){if(settings.resizeMode==="percentage"){dw=Math.round(item.width*settings.percent/100);dh=Math.round(item.height*settings.percent/100);}else{dw=settings.width;dh=settings.height;}}
  if(slug==="crop-image"){sx=settings.cropRect.x;sy=settings.cropRect.y;sw=settings.cropRect.width;sh=settings.cropRect.height;dw=sw;dh=sh;}
  let rotation=0;if(slug==="rotate-image"){const orientation=item.height>=item.width?"portrait":"landscape";rotation=settings.rotationTarget==="all"||settings.rotationTarget===orientation?settings.angle+settings.straighten:0;const radians=Math.abs(rotation)*Math.PI/180;dw=Math.ceil(Math.abs(item.width*Math.cos(radians))+Math.abs(item.height*Math.sin(radians)));dh=Math.ceil(Math.abs(item.width*Math.sin(radians))+Math.abs(item.height*Math.cos(radians)));}
  const canvas=document.createElement("canvas");canvas.width=dw;canvas.height=dh;const context=canvas.getContext("2d");if(!context)throw new Error();context.imageSmoothingEnabled=true;context.imageSmoothingQuality="high";
  if(slug==="rotate-image"){context.translate(dw/2,dh/2);context.rotate(rotation*Math.PI/180);context.drawImage(image,-item.width/2,-item.height/2);}else{if(slug==="convert-to-jpg"){context.fillStyle="#fff";context.fillRect(0,0,dw,dh);}context.drawImage(image,sx,sy,sw,sh,0,0,dw,dh);}
  const mime=slug==="convert-to-jpg"?"image/jpeg":slug==="convert-from-jpg"||slug==="resize-image"?`image/${settings.output}`:item.file.type||"image/png";let blob=await canvasBlob(canvas,mime,settings.quality/100);if(slug==="resize-image"&&settings.targetKB>0&&mime!=="image/png"){for(let q=Math.min(settings.quality/100,.9);blob.size>settings.targetKB*1024&&q>.25;q-=.08)blob=await canvasBlob(canvas,mime,q);}const ext=mime==="image/jpeg"?"jpg":mime.split("/")[1];return{blob,width:dw,height:dh,name:`${baseName(item.file.name)}-${slug}.${ext}`}; }
async function htmlToImage(file:File){const source=await file.text();const documentValue=new DOMParser().parseFromString(source,"text/html");documentValue.querySelectorAll("script,style,noscript").forEach(n=>n.remove());const text=(documentValue.body.innerText||documentValue.body.textContent||"").trim();const canvas=document.createElement("canvas");canvas.width=1200;const lines=wrap(text,92);canvas.height=Math.max(500,100+lines.length*28);const context=canvas.getContext("2d");if(!context)throw new Error();context.fillStyle="#fff";context.fillRect(0,0,canvas.width,canvas.height);context.fillStyle="#0d1748";context.font="700 30px Arial";context.fillText(file.name,55,58);context.font="18px Arial";lines.forEach((line,i)=>context.fillText(line,55,105+i*28));const blob=await canvasBlob(canvas,"image/png",1);return{blob,width:canvas.width,height:canvas.height,name:`${baseName(file.name)}.png`};}
async function universalConvert(item:Item,settings:{output:"jpg"|"png"|"webp"|"svg"|"bmp"|"ico"|"pdf";resize:string;quality:number}){const image=await loadImage(item.sourceUrl);let scale=1;if(["75","50","25"].includes(settings.resize))scale=Number(settings.resize)/100;if(settings.resize==="1920")scale=Math.min(1,1920/Math.max(item.width,item.height));const width=Math.max(1,Math.round(item.width*scale)),height=Math.max(1,Math.round(item.height*scale));const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const context=canvas.getContext("2d");if(!context)throw new Error();if(settings.output==="jpg"){context.fillStyle="#fff";context.fillRect(0,0,width,height);}context.imageSmoothingEnabled=true;context.imageSmoothingQuality="high";context.drawImage(image,0,0,width,height);let blob:Blob;
  if(settings.output==="svg"){const png=canvas.toDataURL("image/png");blob=new Blob([`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><image width="100%" height="100%" href="${png}"/></svg>`],{type:"image/svg+xml"});}
  else if(settings.output==="bmp")blob=bmpBlob(context,width,height);
  else if(settings.output==="ico"){const png=await canvasBlob(canvas,"image/png",1);blob=icoBlob(new Uint8Array(await png.arrayBuffer()),width,height);}
  else if(settings.output==="pdf"){const {PDFDocument}=await import("pdf-lib");const pdf=await PDFDocument.create();const png=await canvasBlob(canvas,"image/png",1);const embedded=await pdf.embedPng(await png.arrayBuffer());const page=pdf.addPage([width,height]);page.drawImage(embedded,{x:0,y:0,width,height});blob=new Blob([await pdf.save()],{type:"application/pdf"});}
  else blob=await canvasBlob(canvas,settings.output==="jpg"?"image/jpeg":`image/${settings.output}`,settings.quality/100);return{blob,width,height,name:`${baseName(item.file.name)}.${settings.output}`};}
function bmpBlob(context:CanvasRenderingContext2D,width:number,height:number){const pixels=context.getImageData(0,0,width,height).data,row=Math.ceil(width*3/4)*4,size=54+row*height,buffer=new ArrayBuffer(size),view=new DataView(buffer);view.setUint16(0,0x424d,true);view.setUint32(2,size,true);view.setUint32(10,54,true);view.setUint32(14,40,true);view.setInt32(18,width,true);view.setInt32(22,height,true);view.setUint16(26,1,true);view.setUint16(28,24,true);let offset=54;for(let y=height-1;y>=0;y--){for(let x=0;x<width;x++){const i=(y*width+x)*4;view.setUint8(offset++,pixels[i+2]);view.setUint8(offset++,pixels[i+1]);view.setUint8(offset++,pixels[i]);}while((offset-54)%row) view.setUint8(offset++,0);}return new Blob([buffer],{type:"image/bmp"});}
function icoBlob(png:Uint8Array,width:number,height:number){const buffer=new Uint8Array(22+png.length),view=new DataView(buffer.buffer);view.setUint16(0,0,true);view.setUint16(2,1,true);view.setUint16(4,1,true);buffer[6]=width>=256?0:width;buffer[7]=height>=256?0:height;view.setUint16(10,1,true);view.setUint16(12,32,true);view.setUint32(14,png.length,true);view.setUint32(18,22,true);buffer.set(png,22);return new Blob([buffer],{type:"image/x-icon"});}
function sourceFormat(file:File){return(file.name.split(".").pop()||file.type.split("/").pop()||"IMG").toUpperCase();}
function wrap(text:string,max:number){const words=text.replace(/\s+/g," ").split(" "),lines:string[]=[];let line="";for(const word of words){if((line+" "+word).trim().length>max&&line){lines.push(line);line=word;}else line=(line+" "+word).trim();}if(line)lines.push(line);return lines;}
function canvasBlob(canvas:HTMLCanvasElement,mime:string,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(v=>v?resolve(v):reject(new Error()),mime,quality));}function readDimensions(url:string){return loadImage(url).then(i=>({width:i.naturalWidth,height:i.naturalHeight}));}function loadImage(url:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=url;});}function baseName(name:string){return name.replace(/\.[^.]+$/,"");}function formatBytes(bytes:number){return bytes<1048576?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/1048576).toFixed(2)} MB`;}
function normalizeAngle(value:number){return ((value%360)+360)%360;}
