import type { Metadata } from "next";
import { DashboardShell } from "../../DashboardShell";
import ConversionTool from "../ConversionTool";

const pageUrl = "https://repetigo.com/pdf-tools/pdf-to-excel";

export const metadata: Metadata = {
  title: "Convert PDF to Excel Free - Extract Tables & Data | RepetiGo",
  description: "Convert PDF to Excel free online - extract tables, data, and financial information from PDF into editable Excel spreadsheets. No sign-up. Files auto-deleted after 60 min.",
  alternates: { canonical: pageUrl },
  openGraph: { title: "Convert PDF to Excel Free - Extract Tables & Data | RepetiGo", description: "Free PDF to Excel converter. Extract tables, data, financial info from PDF into editable spreadsheets. No sign-up, auto-deleted 60 min.", type: "website", url: pageUrl, images: ["https://repetigo.com/og-pdf-to-excel.jpg"] },
  twitter: { card: "summary_large_image", title: "PDF to Excel Converter Free - RepetiGo", description: "Convert PDF to Excel free. Extract tables and data. No sign-up, auto-deleted. India-built." },
  robots: { index: true, follow: true },
};

const pdfToExcelContent = String.raw`H1: Convert PDF to Excel Free. Extract Tables and Data from Any PDF.
RepetiGo's free PDF to Excel converter extracts tables, financial data, and structured information from PDF documents into editable Excel spreadsheets. Upload your PDF, select the pages containing the data you need, and download an .xlsx file ready to open in Microsoft Excel, Google Sheets, or LibreOffice Calc.
The convert pdf to excel free tool works in any browser on any device. No software to install, no account to create, no limit on conversions. Your PDF is automatically deleted from our servers 60 minutes after you download the Excel output.
✓ Extract Tables & Financial Data   ✓ Text & Scanned PDFs   ✓ No Sign-Up   ✓ Auto-Deleted in 60 Minutes

[ Convert PDF to Excel Free - No Sign-Up → repetigo.com/pdf-tools/pdf-to-excel ]

H2: What Does a PDF to Excel Converter Do?
A PDF to Excel converter extracts structured data from a PDF document - primarily tables, rows, columns, and numeric data - and converts it into an Excel spreadsheet format (.xlsx) where each cell can be edited, sorted, filtered, and used in formulas.
This is fundamentally different from simply copying text from a PDF and pasting it into Excel. A PDF does not store data in a structured grid the way Excel does - it stores text as positioned elements on a page. The converter analyses the visual structure of the PDF page to identify table boundaries, column widths, and row separations, then reconstructs that structure as an Excel worksheet.
The accuracy of the conversion depends heavily on the type of PDF - whether it is a text-based PDF or a scanned image PDF. This distinction is important to understand before converting.
💡  A PDF to Excel converter does not unlock a locked PDF or bypass any password protection. It reads the visible content of the PDF page and reconstructs the structure in Excel format. For encrypted PDFs, the password must be removed before conversion.

H2: Text PDF vs Scanned PDF - What Can Be Converted?
H3: Text-Based PDFs - Best Conversion Accuracy
A text-based PDF contains actual text characters in the file - created from a word processor, spreadsheet, or design tool. When you can click and select text in a PDF viewer, it is a text-based PDF. Text PDFs convert to Excel with the highest accuracy because the text is already machine-readable and the table structure can be precisely reconstructed.
Examples of text-based PDFs that convert well: bank statements exported directly from internet banking, invoices generated by accounting software, government data reports downloaded from official websites, financial statements created in Excel and exported to PDF.
H3: Scanned PDFs - OCR Required, Variable Accuracy
A scanned PDF is a photograph of a document - there is no actual text in the file, only an image. When you try to select text in a scanned PDF and it doesn't select, it is a scanned PDF. Converting a scanned PDF to Excel requires OCR (Optical Character Recognition) - technology that reads the image and attempts to identify characters.
OCR accuracy depends on the quality of the scan, the clarity of the original document, the font used, and whether the page is straight (not rotated or skewed). High-quality scans of printed text convert with 85–95% accuracy. Low-quality phone photos, handwritten content, and complex forms may have lower accuracy and require manual correction.
PDF Type
How to Identify
Conversion Accuracy
Best Use For
Text-Based PDF
Can select and copy text in PDF viewer
95–100% - high accuracy
Bank statements, invoices, government data reports, financial statements
Scanned PDF (good quality)
Cannot select text - high-resolution scan of printed document
80–95% - good with some corrections
Printed forms, scanned receipts, physical documents digitised at high DPI
Scanned PDF (low quality)
Cannot select text - phone photo, low resolution, skewed
60–80% - requires significant correction
Not recommended for large data sets. Use for small tables only.
Handwritten PDF
Handwritten content captured in scan
30–60% - very variable
Not recommended. Manual entry is faster for handwritten tables.

📷  If your PDF is a scanned document and the quality is poor, consider re-scanning at 300 DPI with the page flat and straight. The higher the scan quality, the better the Excel conversion accuracy. Use the Rotate PDF tool at /pdf-tools/rotate-pdf to fix a skewed scan before converting.

H2: How to Convert PDF to Excel Free in 3 Steps.
Every conversion follows the same three steps. No account required, no daily limit.
H3: Step 1 - Upload Your PDF File
Click the Upload button or drag and drop your PDF into the upload area. Maximum file size: [SIZE LIMIT]. The tool accepts standard PDF files. Password-protected PDFs must have the protection removed before upload. Upload works on any device - Android phone, iPhone, Windows laptop, Mac, or Chromebook - from your browser. No app download required.
If your PDF is very large (50+ pages) but you only need data from specific pages, consider splitting it first using the Split PDF tool at /pdf-tools/split-pdf. Processing a smaller PDF extracts data faster and more accurately.
H3: Step 2 - Select Pages or Tables
After upload, you can choose to convert the entire document or select specific pages. For large documents with many pages of non-tabular content (text paragraphs, images, headers), selecting only the pages that contain the tables you need produces cleaner output with less manual cleanup required.
The tool extracts all detected tables from the selected pages. If a page contains both text and a table, the table is extracted and the text is not included in the Excel output - the output focuses on structured data, not prose.
H3: Step 3 - Download Your Excel File
Click Convert. Processing time varies by PDF type and complexity - text PDFs convert in a few seconds; scanned PDFs requiring OCR may take 30–60 seconds per page. When complete, your Excel file downloads as an .xlsx file. Each detected table appears as a separate worksheet in the workbook, or all tables appear in sequence on one sheet - depending on the document structure.
📊  The downloaded .xlsx file opens in Microsoft Excel, Google Sheets (upload to Drive), LibreOffice Calc (free, no subscription needed), and any application that reads the Excel format. You do not need Microsoft Excel installed to open the output file.

[ Convert PDF to Excel Free Now → repetigo.com/pdf-tools/pdf-to-excel ]

H2: Why Indian Professionals Convert PDF to Excel.
Use Case
PDF Source
What They Need in Excel
🏦  Bank Statement Analysis
PDF bank statement downloaded from internet banking or sent by email
Transaction amounts, dates, and descriptions extracted into rows. Apply Excel formulas to sum debits, credits, and running balance.
📊  Government Data Reports
PDF reports from RBI, SEBI, Ministry of Finance, Census data portals
Tables of economic data, statistics, and figures extracted for further analysis, charting, or comparison.
🧾  Invoice Processing
PDF invoices received from vendors - standard format across Indian GST-compliant software
Line items, amounts, GST values extracted into Excel for accounts payable processing or reconciliation.
📋  Tender Documents
PDF tender schedules from government procurement portals (GeM, CPPP, state portals)
Item lists, quantities, and specifications extracted into Excel for bid pricing and comparison.
📈  Financial Statements
PDF annual reports, balance sheets, P&L statements from listed companies (BSE, NSE filings)
Financial line items extracted for ratio analysis, comparison across years, or financial modelling.
🎓  Research Data
PDF research papers, surveys, and academic data tables
Statistical tables extracted into Excel for further analysis, chart creation, or data reuse.

H2: Will My PDF Tables Convert Accurately?
Accuracy depends on three factors: the PDF type (text vs scanned), the complexity of the table structure, and the quality of the original document.
Table Type
What It Looks Like
Expected Accuracy
Common Issues
Simple table - fixed columns, clean borders
Standard grid with clear column headers and consistent row formatting
95–100% (text PDF)
Minimal - usually ready to use without correction
Multi-level header table
Headers that span multiple columns or rows
85–95% (text PDF)
Merged header cells may need manual adjustment in Excel
Table without borders
Data aligned visually but without actual cell borders
75–90% (text PDF)
Column alignment depends on whitespace detection - may misalign
Scanned table - good quality
Printed table photographed or scanned at 300 DPI+
80–93%
Minor OCR errors in numbers - always verify totals after conversion
Scanned table - phone photo
Table photographed with phone camera
60–80%
Perspective distortion, shadows, and low DPI reduce accuracy significantly
Tables spanning multiple pages
One table that continues across 2 or more PDF pages
Variable
Multi-page tables may split into separate worksheets - manual merge needed

For financial data - bank statements, invoices, financial statements - always verify the total row in Excel against the original PDF total before using the data. OCR errors in individual number characters are the most common issue in scanned document conversion.

H2: Why Use RepetiGo's PDF to Excel Converter?
Feature
RepetiGo
ilovepdf
Smallpdf
Adobe Acrobat (paid)
Free to use
✓ Always free
✓ Limited free
✓ Limited free
✕ ~₹1,500/month
Sign-up required
✓ Never
✓ Not for basic
~ Optional
✕ Account required
Daily conversion limit
✓ No limit
~ 2 per hour
~ 2 per day
✓ No limit (paid)
Scanned PDF / OCR
✓ Yes
✓ Yes
✓ Yes
✓ Yes
File auto-deleted
✓ 60 minutes
✓ 1 hour
✓ 1 hour
✓ 1 hour
Output format
✓ .xlsx (Excel-compatible)
✓ .xlsx
✓ .xlsx
✓ .xlsx
India-specific use cases
✓ Built for India
✕ Global
✕ Global
✕ Global
Print shop integration
✓ Native PrintPilot
✕ No
✕ No
✕ No

H2: Your PDF Is Safe. Always.
When you upload a PDF to extract financial data - a bank statement, invoice, or company financial report - you are uploading sensitive information. Here is exactly what happens:
Protection Layer
What It Means in Practice
🔒  HTTPS Encrypted Transfer
Your PDF travels from your device to our server over HTTPS (TLS). It cannot be intercepted in transit.
🔐  Isolated Processing Session
Your file is processed in a temporary session with no link to any user account or persistent identifier.
🗑️  Auto-Deleted in 60 Minutes
Your uploaded PDF and the Excel output are automatically and permanently deleted within 60 minutes of download.
👁️  No Data Is Read or Stored
The converter extracts structured data to create the Excel file. No financial data, personal information, or document content is stored, logged, or used for any other purpose.
🚫  No Account = No Data Profile
No sign-up means no personal data is held. No file history, no transaction data, no usage profile.

🔒  Financial PDFs - bank statements, salary slips, tax documents - are among the most sensitive files you can upload to any online tool. RepetiGo processes them in isolated sessions and deletes them within 60 minutes. No financial data is retained beyond the conversion purpose.
Read our Privacy Policy → /security/

H2: PDF to Excel for Print Shops - The Automated Way.
Print shop owners occasionally receive customer documents in PDF format that need to be printed alongside associated data - pricing lists, product specifications, or order forms that originally existed as Excel spreadsheets but were shared as PDFs. The standalone convert PDF to Excel free tool handles one-off conversions.
For print shops integrated with RepetiGo's PrintPilot platform, document processing - including format conversion - is handled automatically as part of the customer document workflow. When a customer uploads a PDF via QR code and the shop owner needs to extract structured data for record-keeping or billing, the PrintPilot dashboard provides access to PDF processing tools without switching applications.
Learn about PrintPilot → /products/printpilot/

[ Try PrintPilot Free → repetigo.com/pricing/ ]
[ Or Convert PDF to Excel Now → repetigo.com/pdf-tools/pdf-to-excel ]

H2: Common Questions - PDF to Excel, Insert PDF in Excel, Copy Tables, and More.
This FAQ covers three related user intents: (1) Converting PDF data into Excel, (2) Inserting a PDF file object into an Excel workbook, and (3) Copying PDF tables manually into Excel.
H3: Q1: How do I convert a PDF to Excel online for free?
Go to repetigo.com/pdf-tools/pdf-to-excel, click Upload and select your PDF file, choose the pages containing the data you want to extract, and click Convert. Your Excel file downloads as an .xlsx workbook. No account is required, no software is needed, and there is no daily limit. The convert pdf to excel free tool works from any browser - on phone or laptop. For text-based PDFs (bank statements, downloaded reports), conversion is fast and accurate. For scanned PDFs, the tool applies OCR before extraction.
H3: Q2: Which pages should I select when converting a PDF to Excel?
Select only the pages that contain the tables or data you need. If your PDF is a 50-page annual report but only pages 12–18 contain the financial tables you want, select only those pages. Selecting the entire document when you only need specific pages produces an Excel file with many empty or text-only worksheets that require manual cleanup. Use the Split PDF tool at /pdf-tools/split-pdf first if you need to extract a specific page range regularly.
H3: Q3: Can I convert a scanned PDF to Excel?
Yes, but with caveats. Scanned PDFs (image-only PDFs where you cannot select text) require OCR before conversion. RepetiGo's tool applies OCR automatically to scanned PDFs. The accuracy depends on scan quality: high-resolution scans (300 DPI) of clearly printed text convert well (80–93% accuracy). Low-quality phone photos of documents convert with lower accuracy (60–80%). For scanned financial documents like paper bank statements or printed receipts, always verify all numeric values in the Excel output against the original PDF before using the data.
H3: Q4: Why does my PDF to Excel conversion have formatting errors?
Several factors cause formatting errors: (1) Scanned PDFs with OCR - the character recognition may misread numbers or symbols, especially in low-quality scans. Always verify financial totals. (2) Complex table structures - tables with merged cells, nested headers, or irregular column spans may not reconstruct perfectly in the Excel grid. (3) Tables without borders - columns aligned visually but without cell borders depend on whitespace detection, which can misalign in conversion. (4) Multi-page tables - a table that continues across PDF pages may split into separate worksheets. For complex tables, partial conversion with manual cleanup is often faster than full manual entry.
H3: Q5: How do I insert a PDF into Excel (as a file attachment)?
This is a different operation from PDF-to-Excel data extraction - inserting a PDF means embedding the PDF file as a clickable object within an Excel workbook, not converting its data. To insert a PDF into Excel: open Excel, go to the Insert tab, click Object (in the Text group), select 'Create from file', click Browse and select your PDF file, tick 'Display as icon' if you want it to appear as an icon rather than the first page of the PDF, and click OK. The PDF appears as an embedded object in your Excel sheet. Double-clicking it opens the PDF in your default PDF viewer. This works in Microsoft Excel on Windows and Mac. It does not extract data - the PDF is attached as a file object.
H3: Q6: How do I copy a table from a PDF to Excel?
There are two methods. Method 1 - using RepetiGo (automatic): Upload the PDF to repetigo.com/pdf-tools/pdf-to-excel, convert, and download the .xlsx file with the table already extracted into Excel cells. Method 2 - manual copy-paste: Open the PDF in a viewer, click at the top-left of the table, drag to select the entire table, copy (Ctrl+C or Cmd+C), open Excel, click cell A1, and paste (Ctrl+V or Cmd+V). For text-based PDFs, this sometimes works well for simple tables. For complex multi-column tables or scanned PDFs, the paste result may not align correctly to columns and requires manual cleanup. RepetiGo's automatic extraction produces cleaner output for multi-column tables.
H3: Q7: How do I save an Excel file as a PDF?
The reverse direction - Excel to PDF - is a built-in Microsoft Excel feature that does not require any external tool. In Excel on Windows or Mac: go to File → Save As → select PDF from the file format dropdown, choose your save location, and click Save. Alternatively: File → Export → Create PDF/XPS → Publish. On Excel for Windows, you can also go to File → Print → select 'Microsoft Print to PDF' printer → Print. In Google Sheets: File → Download → PDF Document. All methods produce a PDF that looks exactly like the Excel spreadsheet. No external converter is needed for Excel→PDF.
H3: Q8: How does RepetiGo compare to Adobe Acrobat for PDF to Excel conversion?
Adobe Acrobat Pro (paid, approximately ₹1,500/month) offers PDF to Excel conversion with advanced table recognition and multi-page table handling. For professional use with very complex PDFs, Acrobat Pro produces the most accurate output. RepetiGo's convert pdf to excel free tool provides the same conversion for standard PDFs at no cost, with no subscription and no account required. For the majority of use cases - bank statements, invoices, government reports, financial tables - RepetiGo's free tool produces comparable accuracy to Adobe's paid product. For highly complex PDFs with irregular layouts, nested headers, or scanned documents at varying DPI, Acrobat Pro has an edge.
H3: Q9: Is it safe to upload my bank statement or financial PDF to a free converter?
RepetiGo uses HTTPS for all file transfers. Your PDF is processed in an isolated session with no user account linkage. The uploaded file and converted output are automatically deleted within 60 minutes of download. No financial data - transaction amounts, account numbers, balances - is stored, logged, or used for any purpose beyond creating your Excel file. That said, for maximum security with highly sensitive financial documents, consider whether a 60-minute retention window is acceptable before uploading. For bank statements used in routine data analysis or expense tracking, RepetiGo's tool is appropriate. For full client financial records or tax authority submissions, you may prefer a locally-installed tool or Adobe Acrobat.
H3: Q10: Can I open the converted Excel file without Microsoft Excel?
Yes. The output file is a standard .xlsx file that opens in: Google Sheets (upload to Google Drive → open with Sheets - free), LibreOffice Calc (free, open-source desktop application for Windows, Mac, Linux), Apache OpenOffice Calc (free), WPS Office Spreadsheets (free mobile and desktop), and Numbers (Mac/iOS - may have formatting differences). You do not need a Microsoft 365 subscription to open or edit .xlsx files. Google Sheets is the most accessible free option - upload the .xlsx to Google Drive and it opens automatically in Sheets.

H2: More Free PDF Tools from RepetiGo.
Tool
What It Does
Link
Compress PDF
Reduce PDF size before converting to Excel
→ /pdf-tools/compress-pdf
Split PDF
Extract specific pages before conversion
→ /pdf-tools/split-pdf
Rotate PDF
Fix scanned PDF orientation before converting
→ /pdf-tools/rotate-pdf
Merge PDF
Combine multiple PDFs before extracting data
→ /pdf-tools/merge-pdf
Word to PDF
Convert Word documents to PDF
→ /pdf-tools/word-to-pdf
JPG to PDF
Convert images to PDF
→ /pdf-tools/jpg-to-pdf
All PDF Tools
Complete PDF tools suite
→ /pdf-tools

[ Convert PDF to Excel Free - No Sign-Up → repetigo.com/pdf-tools/pdf-to-excel ]
[ Explore All PDF Tools → repetigo.com/pdf-tools ]`;

const faqSchemaQuestions = Array.from(pdfToExcelContent.matchAll(/H3: (Q\d+: [^\n]+)\n([\s\S]*?)(?=\nH3: Q\d+:|\nH2:|$)/g)).map((match) => [match[1], match[2].trim()] as const);

export default function PdfToExcelPage() { return <DashboardShell activePath="/pdf-tools"><div className="dashboard generic-pdf-tool-page"><ConversionTool slug="pdf-to-excel"><JsonLd /><article className="tool-seo-content" id="pdf-to-excel-guide"><StructuredSeoCopy content={pdfToExcelContent} /></article></ConversionTool></div></DashboardShell>; }

type SeoTable = { headers: string[]; rows: string[][] };
export function StructuredSeoCopy({ content }: { content: string }) { const normal = separateBlocks(content); return <>{normal.split(/\n{2,}/).map((block, index) => { const text = block.trim(); if (!text) return null; const [first, ...rest] = text.split("\n"); if (first.startsWith("H1: ")) return <h1 key={index}>{first.slice(4)}</h1>; if (first.startsWith("H2: ")) return <h2 key={index}>{first.slice(4)}</h2>; if (first.startsWith("H3: ")) return <h3 key={index}>{first.slice(4)}</h3>; const table = getKnownTable(text); if (table) return <SeoTable key={index} {...table} />; if (first.startsWith("✓")) return <div className="tool-seo-badges" key={index}>{text.split(/\s{2,}/).map((item) => <span key={item}>{item}</span>)}</div>; const ctas = text.split("\n").filter(isCtaLine); if (ctas.length) return <section className="tool-seo-copy-block" key={index}><div className="tool-seo-cta-stack">{ctas.map((line) => <CtaLine key={line} text={line} />)}</div>{rest.filter((line) => !isCtaLine(line)).map((line) => <p key={line}>{renderInlineMappedLinks(line)}</p>)}</section>; return <div className="tool-seo-copy-paragraph" key={index}>{text.split("\n").map((line, lineIndex) => <p key={lineIndex}>{renderInlineMappedLinks(line)}</p>)}</div>; })}</>; }
function separateBlocks(content: string) { const starts = ["PDF Type\nHow to Identify", "Use Case\nPDF Source", "Use Case\nWhy Word? Why PDF?", "Table Type\nWhat It Looks Like", "Format\nSource Application", "Method\nHow It Works", "Element\nWhat Happens During Conversion", "Feature\nRepetiGo", "Protection Layer\nWhat It Means in Practice", "Tool\nWhat It Does"]; const withHeadingBreaks = content.replace(/(^|\n)(H[123]: [^\n]+)\n/g, "$1\n$2\n\n"); return starts.reduce((result, start) => result.replaceAll(`\n${start}`, `\n\n${start}`), withHeadingBreaks); }
function getKnownTable(text: string): SeoTable | null { const lines = text.split("\n").filter(Boolean); const defs = [["PDF Type", "How to Identify", "Conversion Accuracy", "Best Use For"], ["Use Case", "PDF Source", "What They Need in Excel"], ["Use Case", "Why Word? Why PDF?", "India-Specific Context"], ["Table Type", "What It Looks Like", "Expected Accuracy", "Common Issues"], ["Format", "Source Application", "Accepted", "Formatting Preserved"], ["Method", "How It Works", "When to Use", "Limitation"], ["Element", "What Happens During Conversion"], ["Protection Layer", "What It Means in Practice"], ["Tool", "What It Does", "Link"]]; const headers = lines[0] === "Feature" ? lines.slice(0, 5) : defs.find((definition) => definition.every((header, index) => lines[index] === header)); if (!headers) return null; return { headers, rows: chunkRows(lines.slice(headers.length), headers.length) }; }
function chunkRows(values: string[], size: number) { const rows: string[][] = []; for (let index = 0; index < values.length; index += size) rows.push(values.slice(index, index + size)); return rows; }
function SeoTable({ headers, rows }: SeoTable) { return <div className="tool-seo-table-wrap"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.join("|")}>{row.map((cell, index) => <td key={`${cell}-${index}`}>{renderTableCell(cell)}</td>)}</tr>)}</tbody></table></div>; }
function isCtaLine(line: string) { return line.startsWith("[") && line.endsWith("]"); }
function CtaLine({ text }: { text: string }) { const inner = text.slice(2, -2); const arrow = inner.indexOf("→"); const href = mapSeoRoute(arrow >= 0 ? inner.slice(arrow + 1) : ""); return <a className="tool-seo-inline-cta" href={href || "#pdf-to-excel-guide"}>{(arrow >= 0 ? inner.slice(0, arrow) : inner).trim()}{href ? <span>→</span> : null}</a>; }
function renderTableCell(cell: string) { const href = mapSeoRoute(cell.replace(/^→\s*/, "")); return href ? <a className="tool-seo-table-link" href={href}>{getRouteLabel(href)}</a> : renderInlineMappedLinks(cell); }
function renderInlineMappedLinks(text: string) { return text.split(/(repetigo\.com\/(?:tools\/pdf\/[a-z-]+|pricing)\/?|\/tools\/pdf\/[a-z-]*\/?|\/products\/printpilot\/?|\/security\/?)/g).map((part, index) => { const href = mapSeoRoute(part.startsWith("repetigo.com") ? `https://${part}` : part); return href ? <a href={href} key={`${part}-${index}`}>{getRouteLabel(href)}</a> : part; }); }
function mapSeoRoute(route: string) { const clean = route.trim().replace(/^https?:\/\/(www\.)?repetigo\.com/i, "").replace(/\/$/, ""); const routes: Record<string, string> = { "/pdf-tools": "/pdf-tools", "/pdf-tools/pdf-to-excel": "/pdf-tools/pdf-to-excel", "/pdf-tools/compress-pdf": "/pdf-tools/compress-pdf", "/pdf-tools/split-pdf": "/pdf-tools/split-pdf", "/pdf-tools/rotate-pdf": "/pdf-tools/rotate-pdf", "/pdf-tools/merge-pdf": "/pdf-tools/merge-pdf", "/pdf-tools/word-to-pdf": "/pdf-tools/word-to-pdf", "/pdf-tools/jpg-to-pdf": "/pdf-tools/jpg-to-pdf", "/pdf-tools/pdf-to-jpg": "/pdf-tools/pdf-to-jpg", "/products/printpilot": "/print-automation", "/security": "/privacy-policy", "/pricing": "/pricing" }; return routes[clean] || ""; }
function getRouteLabel(href: string) { const labels: Record<string, string> = { "/pdf-tools": "Explore All PDF Tools", "/pdf-tools/pdf-to-excel": "Open PDF to Excel", "/pdf-tools/compress-pdf": "Open Compress PDF", "/pdf-tools/split-pdf": "Open Split PDF", "/pdf-tools/rotate-pdf": "Open Rotate PDF", "/pdf-tools/merge-pdf": "Open Merge PDF", "/pdf-tools/word-to-pdf": "Open Word to PDF", "/pdf-tools/jpg-to-pdf": "Open JPG to PDF", "/pdf-tools/pdf-to-jpg": "Open PDF to JPG", "/print-automation": "Learn About PrintPilot", "/privacy-policy": "Read Privacy Policy", "/pricing": "Start Free Trial" }; return labels[href] || "Open Tool"; }
function JsonLd() { const schemas = [{ "@context": "https://schema.org", "@type": "SoftwareApplication", name: "RepetiGo PDF to Excel Converter", applicationCategory: "BusinessApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "INR" }, description: "Free PDF to Excel converter - extract tables and data from PDF into editable Excel spreadsheets. OCR for scanned PDFs." }, { "@context": "https://schema.org", "@type": "HowTo", name: "How to Convert PDF to Excel Online Free", step: [{ "@type": "HowToStep", name: "Upload PDF" }, { "@type": "HowToStep", name: "Select Pages or Tables" }, { "@type": "HowToStep", name: "Download Excel" }] }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqSchemaQuestions.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://repetigo.com/" }, { "@type": "ListItem", position: 2, name: "PDF Tools", item: "https://repetigo.com/pdf-tools" }, { "@type": "ListItem", position: 3, name: "PDF to Excel", item: pageUrl }] }]; return <>{schemas.map((schema) => <script key={schema["@type"]} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}</>; }
