import type { Metadata } from "next";
import Link from "next/link";
import { AlertTriangle, ArrowRight, Check, FileText, Lock, Scale, ShieldCheck, Sparkles } from "lucide-react";
import { LandingNavbar } from "../LandingNavbar";
import { PublicFooter } from "../PublicFooter";

export const metadata: Metadata = {
  title: "Terms & Conditions - RepetiGo",
  description:
    "Read the RepetiGo Terms & Conditions governing use of our AI-powered print shop software, secure document upload, document processing, subscriptions, and related services.",
};

const effectiveDate = "1 July 2025";

const definitions = [
  ["RepetiGo / we / us / our", "RepetiGo and its affiliated legal entities operating this Platform."],
  ["Platform", "The RepetiGo website, web application, software, APIs, tools, and all related services."],
  ["User / you", "Any person or entity accessing or using the Platform in any capacity."],
  ["Shop Owner / Business User", "A cyber cafe, print shop, CSC centre, or business that subscribes to RepetiGo."],
  ["End Customer", "A person who visits a participating shop and uses the QR-based document upload service."],
  ["Account", "A registered account on the Platform, including all data and settings associated with it."],
  ["Document", "Any file - PDF, image, Office document, or other format - uploaded to the Platform."],
  ["Services", "All features made available through the Platform, including PrintPilot, PDF Tools, OCR, AI processing, and future services."],
  ["Content", "All text, data, files, images, and other materials uploaded, submitted, or generated by users on the Platform."],
  ["Subscription", "A paid plan that grants a Business User access to Platform features for a defined period."],
  ["Intellectual Property", "Patents, trademarks, copyrights, trade secrets, software, algorithms, designs, and related rights."],
];

const services = [
  ["PrintPilot", "Core print shop management - QR upload, AI processing, job queue, and direct printer integration."],
  ["Secure QR Document Upload", "End-to-end encrypted document upload via QR code - no personal WhatsApp or email required."],
  ["AI Document Processing", "Automated image enhancement, page detection, resizing, and print optimization."],
  ["OCR", "Optical Character Recognition for extracting text from images and scanned documents."],
  ["PDF Tools", "PDF creation, merging, splitting, compression, and format conversion."],
  ["Passport Photo Tools", "Automated generation of government-standard passport and ID photos."],
  ["Image Enhancement", "Quality improvement, colour correction, and optimisation for print output."],
];

const thirdParties = [
  ["Cloud Infrastructure", "AWS / Google Cloud or equivalent", "Hosting, computing, and data storage"],
  ["Payment Gateway", "Razorpay, Cashfree, PhonePe Business, or equivalent", "Secure payment processing"],
  ["Analytics", "Google Analytics or equivalent", "Platform usage analysis and improvement"],
  ["Email Service", "SendGrid, AWS SES, or equivalent", "Account notifications, receipts, OTPs"],
  ["SMS Provider", "MSG91, Twilio, or equivalent", "OTPs and critical alerts"],
  ["AI Services", "Disclosed when used", "AI-powered document processing features"],
  ["Customer Support", "Freshdesk or equivalent", "Managing user support requests"],
];

const contactRows = [
  ["Company Name", "RepetiGo Technologies Pvt. Ltd. [confirm legal entity before publishing]"],
  ["Registered Address", "[Full address, city, state, PIN code, India]"],
  ["General Support", "support@repetigo.com"],
  ["Legal & Compliance", "legal@repetigo.com"],
  ["Billing", "billing@repetigo.com"],
  ["Security", "security@repetigo.com"],
  ["Phone", "+91 XXXXXXXXXX"],
  ["Website", "https://repetigo.com"],
];

type TermsSectionData = {
  id: string;
  title: string;
  body?: string[];
  bullets?: string[];
  warning?: string;
  groups?: [string, string][];
  table?: string[][];
};

const sections: TermsSectionData[] = [
  {
    id: "introduction",
    title: "1. Introduction",
    body: [
      "Welcome to RepetiGo. These Terms & Conditions govern your use of the RepetiGo platform, including our website, software products, APIs, and all related services.",
      "RepetiGo is an AI-powered print shop software and secure document infrastructure platform. We help cyber cafes, print shops, Xerox centres, CSC centres, businesses, and individuals automate document workflows - from secure QR-based uploads through AI processing to direct printer delivery.",
      "By accessing or using RepetiGo, you confirm that you have read, understood, and agree to be bound by these Terms and our Privacy Policy. If you do not agree, you must not use the Platform.",
      "These Terms apply to all users of the RepetiGo Platform, including shop owners, business subscribers, and end customers who access the Platform through a participating print shop.",
    ],
  },
  {
    id: "definitions",
    title: "2. Definitions",
    table: definitions,
  },
  {
    id: "eligibility",
    title: "3. Eligibility",
    groups: [
      ["Age Requirement", "You must be at least 18 years old to create an account or enter into these Terms. Users under 18 may use the Platform only under supervision of a parent or legal guardian."],
      ["Legal Capacity", "You represent that you can form a binding contract, are not prohibited from using the Platform, and have authority to accept these Terms for yourself or your organisation."],
      ["Business Users", "Business users must have authority to bind their organisation, operate legally, and ensure staff and end customers comply with these Terms."],
      ["Geographic Eligibility", "The Platform is currently offered in India. Users elsewhere must ensure their access complies with local laws."],
    ],
  },
  {
    id: "account-registration",
    title: "4. Account Registration",
    groups: [
      ["Accurate Information", "You must provide accurate, complete, and current account information and update it promptly if it changes."],
      ["Account Security", "You are responsible for keeping credentials confidential, all activity under your account, and logging out from shared devices."],
      ["Unauthorized Access", "Notify us immediately at security@repetigo.com if you become aware of unauthorized account use or a security breach."],
      ["One Account Per User", "Unless expressly permitted by us, each person may maintain only one individual account."],
    ],
  },
  {
    id: "acceptable-use",
    title: "5. Acceptable Use",
    body: ["You agree to use the Platform only for lawful purposes and in a manner consistent with these Terms."],
    bullets: [
      "Do not upload illegal, malicious, fraudulent, forged, infringing, defamatory, hateful, obscene, or privacy-violating content.",
      "Do not attempt unauthorized access, reverse engineering, scraping, infrastructure abuse, payment bypass, vulnerability exploitation, spam, impersonation, or access to printers not assigned to you.",
      "RepetiGo may investigate suspected violations, suspend or terminate accounts, report violations to authorities, and take legal action where appropriate.",
    ],
  },
  {
    id: "services",
    title: "6. Services",
    table: services,
    body: [
      "We may introduce additional services such as Digital Locker, eSign, Cloud Printing, Developer APIs, Workflow Automation, and Enterprise Document Management. Future services may be subject to additional terms.",
      "We reserve the right to modify, suspend, or discontinue any service or feature at any time, with or without notice.",
    ],
  },
  {
    id: "document-processing",
    title: "7. Document Processing",
    groups: [
      ["Processing Scope", "RepetiGo processes documents solely to deliver the requested service, such as printing, PDF conversion, OCR, or image enhancement."],
      ["User Responsibility", "You are responsible for uploading the correct document, verifying order and orientation, selecting print settings, choosing output destination, and ensuring content is lawful."],
      ["Automatic File Deletion", "Uploaded documents are automatically deleted after the requested service is completed or after the configured retention period expires, whichever occurs first."],
      ["No Verification", "RepetiGo does not verify identity, ownership, authenticity, validity, legality, or regulatory compliance of uploaded documents."],
    ],
    warning:
      "RepetiGo is a technology platform. We do not verify the accuracy, legality, or authenticity of any document uploaded to the Platform. Users bear full legal responsibility for their uploads.",
  },
  {
    id: "ai-features",
    title: "8. AI Features",
    bullets: [
      "AI features may include OCR, image enhancement, background removal, auto cropping, noise reduction, document detection, and file optimisation.",
      "AI processing may produce imperfect results. You should review AI-processed documents before confirming print jobs.",
      "Uploaded documents are not used to train public AI models without explicit informed consent. AI processing is performed to complete the requested service.",
    ],
  },
  {
    id: "payments",
    title: "9. Payments",
    groups: [
      ["Payment Processing", "Payments are processed by certified third-party payment gateways. By making a payment, you also agree to the payment gateway's terms."],
      ["No Card Storage", "RepetiGo does not store or access full card numbers, CVV, UPI PIN, or complete payment credentials."],
      ["Taxes", "Fees are exclusive of applicable taxes unless stated otherwise. You are responsible for applicable taxes including GST."],
      ["Payment Errors", "Contact billing@repetigo.com within 7 days if you believe a payment error occurred."],
      ["Refund Policy", "Refund eligibility is governed by our separate Refund Policy. Review it before making a purchase."],
    ],
  },
  {
    id: "business-accounts",
    title: "10. Business Accounts & Subscriptions",
    bullets: [
      "Business users may subscribe to paid plans described on the Pricing page.",
      "Subscriptions renew monthly or annually unless cancelled before renewal.",
      "Cancellation takes effect at the end of the current billing period. Pro-rated refunds are not provided unless required by law.",
      "Upgrades take effect immediately and may be prorated. Downgrades take effect at the next billing cycle.",
      "If payment fails, we may suspend or downgrade the account until payment is resolved.",
      "The account administrator manages access, compliance, and all business account activity.",
    ],
  },
  {
    id: "intellectual-property",
    title: "11. Intellectual Property",
    groups: [
      ["RepetiGo IP", "RepetiGo and its licensors own the Platform, software code, algorithms, trademarks, UI design, documentation, AI models, databases, and analytical outputs."],
      ["User Content Ownership", "You retain ownership of documents and content you upload. Uploading does not transfer ownership to RepetiGo."],
      ["Limited License", "You grant RepetiGo a limited, temporary, non-exclusive license to process, store, and transmit content solely to deliver the requested service."],
      ["Copyright Responsibility", "You must have the legal right to upload any submitted document and are responsible for infringement claims arising from user-uploaded content."],
    ],
  },
  {
    id: "platform-license",
    title: "12. License to Use the Platform",
    bullets: [
      "Subject to compliance, RepetiGo grants you a limited, non-exclusive, non-transferable, revocable license to access and use the Platform for personal or internal business purposes.",
      "You may not sublicense, sell, resell, transfer, modify, adapt, create derivative works, build a competing product, or remove proprietary notices from the Platform.",
    ],
  },
  {
    id: "third-party-services",
    title: "13. Third-Party Services",
    table: thirdParties,
    body: [
      "These third-party services operate under their own terms and privacy policies. RepetiGo is not responsible for their practices, availability, or performance.",
      "Review and update the provider list with actual third-party providers before publishing.",
    ],
  },
  {
    id: "availability",
    title: "14. Service Availability",
    bullets: [
      "We make commercially reasonable efforts to keep the Platform available and reliable, but do not guarantee 100% uptime.",
      "Planned maintenance may require downtime. Where reasonably practicable, we will provide advance notice.",
      "Unplanned outages may occur due to infrastructure failures, third-party disruptions, security incidents, or other technical issues.",
      "Unless a separate SLA is signed, no uptime guarantee is provided.",
    ],
  },
  {
    id: "liability",
    title: "15. Limitation of Liability",
    warning: "Please read this section carefully. It limits RepetiGo's legal liability to you in important ways.",
    bullets: [
      "To the maximum extent permitted by law, RepetiGo is not liable for indirect, incidental, special, consequential, punitive damages, lost profits, lost revenue, business interruption, loss of goodwill, or loss of data beyond gross negligence.",
      "RepetiGo is not liable for wrong documents, incorrect print settings, printer failures, hardware issues, internet failures, payment gateway errors, misuse, user error, print quality differences, or consequences from user-uploaded content.",
      "Where liability cannot be excluded, total liability will not exceed the greater of the amount paid to RepetiGo in the previous 3 months or INR 1,000.",
    ],
  },
  {
    id: "indemnification",
    title: "16. Indemnification",
    body: [
      "You agree to defend, indemnify, and hold harmless RepetiGo, its directors, employees, agents, partners, and licensors from claims, liabilities, damages, losses, costs, and expenses arising from your violation of these Terms, applicable law, uploaded content, fraudulent or illegal documents, unauthorized platform use, misrepresentation, negligence, or wilful misconduct.",
    ],
  },
  {
    id: "termination",
    title: "17. Termination",
    bullets: [
      "RepetiGo may suspend, restrict, or terminate access if you violate Terms, engage in fraudulent or illegal activity, upload risky content, cause payment fraud, create security risk, or if required by law.",
      "You may close your account by contacting support@repetigo.com.",
      "Upon termination, your license ends, access to account data may cease, outstanding fees become due, and surviving legal provisions continue to apply.",
    ],
  },
  {
    id: "security-confidentiality",
    title: "18. Data Security & Confidentiality",
    bullets: [
      "Security safeguards include encryption in transit, encryption at rest, secure authentication, role-based access, secure cloud infrastructure, automatic file deletion, security monitoring, audit logs, and rate limiting.",
      "Uploaded documents are treated as confidential, accessed only to deliver requested services, never sold or disclosed to unauthorised parties, and automatically deleted after the configured retention period.",
    ],
  },
  {
    id: "export-control",
    title: "19. Export Control",
    body: [
      "You agree to comply with all applicable Indian and international export control laws, regulations, and trade sanctions in connection with your use of the Platform.",
    ],
  },
  {
    id: "governing-law",
    title: "20. Governing Law",
    bullets: [
      "These Terms are governed by the laws of India, without regard to conflict-of-law principles.",
      "Courts in [insert city, e.g. New Delhi / Mumbai / Bengaluru] shall have exclusive jurisdiction, subject to the Dispute Resolution section.",
      "Applicable laws include the Information Technology Act, 2000, Digital Personal Data Protection Act, 2023, Consumer Protection Act, 2019, Indian Contract Act, 1872, and Copyright Act, 1957.",
    ],
  },
  {
    id: "dispute-resolution",
    title: "21. Dispute Resolution",
    groups: [
      ["Informal Resolution", "Contact legal@repetigo.com first. We will respond within 15 business days and make a good-faith effort to resolve the concern."],
      ["Arbitration", "If included after legal review, disputes may be referred to binding arbitration under the Arbitration and Conciliation Act, 1996, with seat in [insert city]."],
      ["Class Action Waiver", "To the extent permitted by law, disputes must be resolved individually and not through class, collective, or representative proceedings."],
    ],
  },
  {
    id: "force-majeure",
    title: "22. Force Majeure",
    body: [
      "RepetiGo will not be liable for delay or failure caused by events beyond reasonable control, including natural disasters, war, government actions, telecom failures, cyberattacks, pandemics, power failures, labour disputes, or third-party cloud outages.",
    ],
  },
  {
    id: "changes",
    title: "23. Changes to Terms",
    bullets: [
      "We may update these Terms to reflect service, legal, or business changes.",
      "For material changes, we will update the Effective Date, notify active business users by email at least 14 days in advance, post a platform notice, and may request fresh acceptance.",
      "Continued use after updated Terms take effect constitutes acceptance.",
    ],
  },
  {
    id: "entire-agreement",
    title: "24. Entire Agreement, Severability & Waiver",
    groups: [
      ["Entire Agreement", "These Terms, our Privacy Policy, and referenced policies constitute the entire agreement regarding Platform use."],
      ["Severability", "If any provision is invalid or unenforceable, it will be limited or eliminated to the minimum extent necessary and the rest remains in effect."],
      ["Waiver", "Failure or delay in exercising rights is not a waiver. Any waiver must be written and signed by an authorised RepetiGo representative."],
    ],
  },
  {
    id: "contact",
    title: "25. Contact Information",
    table: contactRows,
    body: ["We aim to respond to all legal and compliance enquiries within 10 business days."],
  },
];

const faqs = [
  ["Who is responsible if I upload the wrong document?", "You are. RepetiGo processes documents exactly as uploaded and does not verify content, order, or accuracy."],
  ["Does RepetiGo own my uploaded documents?", "No. You retain ownership. RepetiGo processes documents only to deliver the requested service."],
  ["Can I upload any type of document?", "You may upload documents you own or have the right to print. Illegal, forged, infringing, or prohibited content is not allowed."],
  ["What if print quality is not what I expected?", "Print quality depends on printer, ink, paper, and shop hardware outside RepetiGo's control. Always preview before confirming."],
  ["Can RepetiGo be held liable if a print job fails?", "Liability is limited as described in Section 15. RepetiGo is not liable for hardware issues, outages, or incorrect user settings."],
  ["Are my documents stored permanently?", "No. Documents are automatically deleted after printing is complete or after the configured retention period."],
  ["What if I want to cancel my business subscription?", "You can cancel from account settings or support. Cancellation takes effect at the end of the current billing period."],
  ["Can RepetiGo terminate my account?", "Yes, if you violate these Terms, engage in illegal activity, upload prohibited content, or create security or legal risk."],
  ["What law governs these Terms?", "These Terms are governed by Indian law and subject to courts in the selected jurisdiction city."],
  ["How will I know if these Terms change?", "We will notify active business users by email at least 14 days before material changes take effect and post a platform notice."],
];

export default function TermsConditionsPage() {
  return (
    <main className="terms-shell">
      <LandingNavbar />

      <section className="terms-hero">
        <div className="terms-container">
          <span className="terms-kicker">
            <Scale size={14} /> Terms & Conditions
          </span>
          <h1>Enterprise-Grade Legal Agreement for RepetiGo.</h1>
          <p>
            These Terms govern use of RepetiGo's AI-powered print shop software, secure document upload, document
            processing, subscriptions, APIs, and related services.
          </p>
          <div className="terms-hero-meta">
            <span>Effective Date: {effectiveDate}</span>
            <span>Production-ready legal draft</span>
          </div>
        </div>
      </section>

      <section className="terms-layout terms-container">
        <aside className="terms-index">
          <strong>On this page</strong>
          <nav aria-label="Terms sections">
            {sections.map((section) => (
              <a href={`#${section.id}`} key={section.id}>
                {section.title}
              </a>
            ))}
            <a href="#faq">26. Frequently Asked Questions</a>
            <a href="#conclusion">27. Conclusion</a>
          </nav>
        </aside>

        <div className="terms-content">
          <div className="terms-notice">
            <AlertTriangle size={20} />
            <p>
              This document includes placeholders for legal entity details, jurisdiction, payment providers, and contact
              channels. Review those fields with counsel before publishing.
            </p>
          </div>

          {sections.map((section) => (
            <TermsSection section={section} key={section.id} />
          ))}

          <section className="terms-card" id="faq">
            <span className="terms-section-label">Section 26</span>
            <h2>26. Frequently Asked Questions</h2>
            <p className="terms-lead">
              These questions help ordinary users quickly understand their rights and obligations under these Terms.
            </p>
            <div className="terms-faq-list">
              {faqs.map(([question, answer], index) => (
                <details key={question}>
                  <summary>
                    <span>Q{index + 1}: {question}</span>
                    <strong>+</strong>
                  </summary>
                  <p>{answer}</p>
                </details>
              ))}
            </div>
          </section>

          <section className="terms-card terms-conclusion" id="conclusion">
            <span className="terms-section-label">Section 27</span>
            <h2>27. Conclusion</h2>
            <p>
              These Terms & Conditions are designed to be clear, transparent, and fair - for you and for us.
              RepetiGo is built on a simple promise: make document printing private, smart, and effortless for Indian
              print businesses.
            </p>
            <p>
              If you have any questions about these Terms, or if there is anything you do not understand, please reach
              out before using the Platform.
            </p>
            <Link href="/contact-us">
              Contact RepetiGo <ArrowRight size={17} />
            </Link>
          </section>
        </div>
      </section>
      <PublicFooter />
    </main>
  );
}

function TermsSection({ section }: { section: TermsSectionData }) {
  return (
    <section className="terms-card" id={section.id}>
      <span className="terms-section-label">Section {section.title.split(".")[0]}</span>
      <h2>{section.title}</h2>

      {section.body?.map((paragraph) => (
        <p key={paragraph}>{paragraph}</p>
      ))}

      {section.warning ? (
        <div className="terms-warning">
          <ShieldCheck size={18} />
          <p>{section.warning}</p>
        </div>
      ) : null}

      {section.groups ? (
        <div className="terms-group-list">
          {section.groups.map(([title, body]) => (
            <article key={title}>
              <h3>{title}</h3>
              <p>{body}</p>
            </article>
          ))}
        </div>
      ) : null}

      {section.bullets ? (
        <ul className="terms-bullets">
          {section.bullets.map((bullet) => (
            <li key={bullet}>
              <Check size={16} />
              <span>{bullet}</span>
            </li>
          ))}
        </ul>
      ) : null}

      {section.table ? (
        <div className="terms-table-wrap">
          <table>
            <tbody>
              {section.table.map((row) => (
                <tr key={row.join("-")}>
                  {row.map((cell, index) => (
                    <td key={cell} className={index === 0 ? "terms-table-key" : undefined}>
                      {cell}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : null}
    </section>
  );
}
